### ISSUE TITLE
[BUG]: Installation fails with Python 3.12

### ISSUE THREAD

**Issue by ismail** [modularml/mojo#1070]
Trying to do `modular install mojo` on an M2 Mac with Python 3.12 as default fails with:

```
Traceback (most recent call last):
  File "/Users/ismail/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 29, in <module>
    import papermill as pm
  File "/Users/ismail/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/papermill/__init__.py", line 3, in <module>
    from .exceptions import PapermillException, PapermillExecutionError
  File "/Users/ismail/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/papermill/exceptions.py", line 3, in <module>
    from ansiwrap import strip_color
  File "/Users/ismail/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/ansiwrap/__init__.py", line 1, in <module>
    from .core import *
  File "/Users/ismail/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/ansiwrap/core.py", line 6, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
modular: error: failed to run python:
```

There is a possible fix at https://github.com/jonathaneunice/ansiwrap/pull/20, but it's not merged yet.

**Comment by Moosems** [comment]
See #1011

**Comment by robertbcalhoun** [comment]
Encountered the same issue when installing on Debian 11 with Python 3.12; worked around by downgrading Python 3.11.

**Comment by robertbcalhoun** [comment]
See https://github.com/modularml/mojo/issues/1102

**Comment by jackos** [comment]
Hi @ismail this should be resolved now, please reopen if you have any other problems with Python 3.12
