### ISSUE TITLE
[Modular CLI]: Python 3.12 Unsupported issues

### ISSUE THREAD

**Issue by aaronsaikovski-tl** [modularml/mojo#1102]
### Issue description

Error appears when running:
modular install mojo

Traceback (most recent call last):
  File "/Users/<someuser>/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 29, in <module>
    import papermill as pm
  File "/Users/<someuser>/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/papermill/__init__.py", line 3, in <module>
    from .exceptions import PapermillException, PapermillExecutionError
  File "/Users/<someuser>/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/papermill/exceptions.py", line 3, in <module>
    from ansiwrap import strip_color
  File "/Users/<someuser>/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/ansiwrap/__init__.py", line 1, in <module>
    from .core import *
  File "/Users/<someuser>/.modular/pkg/packages.modular.com_mojo/venv/lib/python3.12/site-packages/ansiwrap/core.py", line 6, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
modular: error: failed to run python:

### Steps to reproduce

Followed steps from here: https://developer.modular.com/download

### Version Info

```shell
modular 0.2.1 (5144fffe)
Mac OS Sonoma 14.0
```

**Comment by Moosems** [comment]
Related to #1101

**Comment by bbnickell** [comment]
Able to confirm that I ran into this as well.

(python_312) nickell@mlm1 % modular -v
modular 0.2.2 (95d42445)
(python_312) nickell@mlm1 % uname -a
Darwin mlm1 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm6

**Comment by jackos** [comment]
Hi @aaronsaikovski-tl this should be resolved now, please reopen if you have any other problems with Python 3.12
