### ISSUE TITLE
[BUG] Ubuntu install fails for both MAX and MOJO

### ISSUE THREAD

**Issue by mxsur** [modularml/mojo#2071]
### Bug description

Installing both `max` and `mojo` fails with the same error

```
❯ modular install mojo

# Found release for https://packages.modular.com/mojo @ 24.2.0-c2427bc5-release
# Downloading archive: packages/24.2.0-c2427bc5-release/mojo-x86_64-unknown-linux-gnu-24.2.0-c2427bc5-release-11-0.tar.gz
Done         [ ███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ ] 100%     198MiB/198MiB @  10.2MiB/s
# Extracting downloaded archives. 
# Extraction complete, setting configs...
# Configs complete, running post-install hooks...
Traceback (most recent call last):
  File "/home/maksym/.local/share/modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 529, in <module>
    main()
  File "/home/maksym/.local/share/modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 518, in main
    tester = Tester(
             ^^^^^^^
  File "/home/maksym/.local/share/modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 94, in __init__
    mojo_python_library = config.get(
                          ^^^^^^^^^^^
  File "/home/maksym/miniconda3/lib/python3.12/configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maksym/miniconda3/lib/python3.12/configparser.py", line 1130, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mojo'
modular: error: failed to run script
==========================
Failure Information:
        - Script: `PATH=/home/maksym/miniconda3/bin:/home/maksym/miniconda3/condabin:/home/maksym/.wasmedge/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/maksym/.cabal/bin:/home/maksym/.ghcup/bin:/home/maksym/.krew/bin:/home/maksym/.wasmer/bin:/home/maksym/.wasmtime/bin:/home/maksym/.juliaup/bin:/home/maksym/.local/bin:/home/maksym/.cargo/bin:/home/maksym/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/maksym/go/bin:/home/maksym/.temporalio/bin HOME=/home/maksym PYTHONPATH=/home/maksym/.local/share/modular/pkg/packages.modular.com_mojo/venv/lib/home/maksym/.local/share/modular/pkg/packages.modular.com_mojo/venv/bin/python /home/maksym/.local/share/modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py --modular-home /home/maksym/.local/share/modular --package-path /home/maksym/.local/share/modular/pkg/packages.modular.com_mojo --mojo-config-section mojo`
        - Result: 1
        - Stderr:
Traceback (most recent call last):
  File "/home/maksym/.local/share/modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 529, in <module>
    main()
  File "/home/maksym/.local/share/modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 518, in main
    tester = Tester(
             ^^^^^^^                                                                                                                                                                         
  File "/home/maksym/.local/share/modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 94, in __init__                                                             
    mojo_python_library = config.get(                                                                                                                                                        
                          ^^^^^^^^^^^                                                                                                                                                        
  File "/home/maksym/miniconda3/lib/python3.12/configparser.py", line 759, in get                                                                                                            
    d = self._unify_values(section, vars)                                                                                                                                                    
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maksym/miniconda3/lib/python3.12/configparser.py", line 1130, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mojo'


==========================

```

### Steps to reproduce

modular install max && modular install mojo

### System information

```shell
- What OS did you do install Mojo on ?
❯ neofetch
           `-mddhhhhhhhhhddmss`              
        ./mdhhhhhhhhhhhhhhhhhhhhhh.         ----------                                                                                                                                       
     :mdhhhhhhhhhhhhhhhhhhhhhhhhhhhm`       OS: Lubuntu 22.04.4 LTS x86_64                                                                                                                   
   :ymhhhhhhhhhhhhhhhyyyyyyhhhhhhhhhy:      Host: VivoBook_ASUSLaptop X521FL_S533FL 1.0                                                                                                      
  `odhyyyhhhhhhhhhy+-`./syhhhhhhhho`     Kernel: 6.2.0-1009-lowlatency                                                                                                                    
 `hhy..:oyhhhhhhhy-`:osso/..:/++oosyyyh`    Uptime: 4 hours, 6 mins                                                                                                                          
 dhhs   .-/syhhhhs`shhhhhhyyyyyyyyyyyyhs    Packages: 2714 (dpkg), 18 (flatpak), 16 (snap)                                                                                                   
:hhhy`  yso/:+syhy/yhhhhhshhhhhhhhhhhhhh:   Shell: bash 5.1.16                                                                                                                               
hhhhho. +hhhys++oyyyhhhhh-yhhhhhhhhhhhhhs   Resolution: 1920x1080, 1920x1080                                                                                                                 
hhhhhhs-`/syhhhhyssyyhhhh:-yhhhhhhhhhhhhh   DE: LXQt 1.4.0                                                                                                                                   
hhhhhhs  `:/+ossyyhyyhhhhs -yhhhhhhhhhhhh   WM: Openbox                                                                                                                                      
hhhhhhy/ `syyyssyyyyhhhhhh: :yhhhhhhhhhhs   Theme: Arc-Dark [GTK2/3]                                                                                                                         
:hhhhhhyo:-/osyhhhhhhhhhhho  ohhhhhhhhhh:   Icons: ePapirus [GTK2/3]                                                                                                                         
 sdhhhhhhhyyssyyhhhhhhhhhhh+  +hhhhhhhhs    Terminal: qterminal                                                                                                                              
 `shhhhhhhhhhhhhhhhhhhhhhy+` .yhhhhhhhh`    Terminal Font: Fira Code 13                                                                                                                      
  +sdhhhhhhhhhhhhhhhhhyo/. `/yhhhhhhhd`     CPU: Intel i5-10210U (8) @ 4.200GHz                                                                                                              
   `:shhhhhhhhhh+---..``.:+yyhhhhhhh:       GPU: NVIDIA GeForce MX250                                                                                                                        
     `:mdhhhhhh/.syssyyyyhhhhhhhd:`         GPU: Intel CometLake-U GT2 [UHD Graphics]                                                                                                        
        `+smdhhh+shhhhhhhhhhhhdm`           Memory: 3970MiB / 7741MiB                                                                                                                        
           `sNmdddhhhhhhhddm-`     

- Provide version information for Mojo by pasting the output of `mojo -v`
`NA`
- Provide Modular CLI version by pasting the output of `modular -v`
`modular 0.6.0 (04c05243)`
```

**Comment by ematejska** [comment]
This is not a supported platform.  Please see https://docs.modular.com/mojo/manual/get-started/#system-requirements for the supported platforms.
