### ISSUE TITLE
[BUG] Jupyter fails to start kernel after re-installing Mojo 24.2

### ISSUE THREAD

**Issue by rabainu** [modularml/mojo#2159]
### Bug description

Trying to execute a Jupyter cell with Mojo kernel leads to error:

```
Failed to start the Kernel. 
ImportError: cannot import name 'text_encoding' from 'io' (unknown location). 
View Jupyter [log](command:jupyter.viewOutput) for further details.
```

In Jupyter log it says

```
Disposing kernel process due to an error Error: The kernel died. Error: Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "~/miniconda3/lib/python3.12/io.py", line 55, in <module>
```

### Steps to reproduce

I have a conda virtual environment set up as in https://docs.modular.com/mojo/manual/python/. In addition I have a homebrew python3.11 and 3.12 and /usr/bin/python3. When importing Python and sys-module in Mojo REPL I get the conda Python version and sys.path information and I can run all my conda installed Python packages in Mojo 24.2. In VS Code I have python.defaultInterpreterPath set to ~/miniconda3/bin/python

Before reinstalling I was able to execute cells in Jupyter except for the %%python magic command. Looking for a solution to this I reinstalled yesterday mojo with:

```
modular uninstall mojo
modular clean
modular install mojo
```

After the reinstallation everything was working except that Jupyter fails to start the kernel. When diagnosing this problem I noticed that trying to run the system /usr/bin/python3 leads to the same error as when trying to execute a Jupyter notebook cell, which makes me suspect that mojo Jupyter kernel is confused with the /usr/bin/ version of Python on my system.

```
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "/Users/mmiettin/miniconda3/lib/python3.12/io.py", line 55, in <module>
ImportError: cannot import name 'text_encoding' from 'io' (unknown location)
```

### System information

```shell
- What OS did you do install Mojo on ?

macOS Sonoma 14.4.1 (M1)

- Provide version information for Mojo by pasting the output of `mojo -v`

mojo 24.2.0 (c2427bc5)

- Provide Modular CLI version by pasting the output of `modular -v`

modular 0.5.2 (6b3a04fd)
```

**Comment by rabainu** [comment]
I updated to the latest modular version 0.6.0 and reinstalled and after everything works including the Jupyter magic command %%python.
