### ISSUE TITLE
[modular CLI] install mojo failing on Ubuntu Linux with spack-installed Python

### ISSUE THREAD

**Issue by tylerjereddy** [modularml/mojo#2271]
Python `3.11.7` installed via `spack` (common to use at US National Labs), on a desktop running `Ubuntu 22.04.2 LTS`. Running the `modular install mojo` command within a Python `venv`. Looks like it is hitting a segfault trying to install the Python dependencies, which probably shouldn't happen.

<details>
<summary> Error output below the fold </summary>

```
# Found release for https://packages.modular.com/mojo @ 24.2.1-2f0dcf11-release
# Downloading archive: packages/24.2.1-2f0dcf11-release/mojo-x86_64-unknown-linux-gnu-24.2.1-2f0dcf11-release-12-0.tar.gz
Downloaded   [ ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ ] 100%     198MiB/198MiB             
# Extracting downloaded archives. 
Extracted    [ ████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ ] 100%     198MiB/198MiB             
# Extraction complete, setting configs...
# Configs complete, running post-install hooks...
An error occurred when installing Python dependencies:
stdout:

stderr:


Traceback (most recent call last):
  File "/home/treddy/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 75, in <module>
    main()
  File "/home/treddy/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 63, in main
    _check_call(
  File "/home/treddy/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 34, in _check_call
    raise e
  File "/home/treddy/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 22, in _check_call
    subprocess.run(
  File "/home/treddy/github_projects/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/python-3.11.7-576sy6uczetw3xyazw7g5tta7ei4s5jl/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/home/treddy/.modular/pkg/packages.modular.com_mojo/venv/bin/python', '-m', 'pip', 'install', '-r', '/home/treddy/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt')' died with <Signals.SIGSEGV: 11>.
modular: error: failed to run script
==========================
Failure Information:
	- Script: `PATH=/home/treddy/python_venvs/py_311_bench_ecr/bin:/home/treddy/.local/bin:/home/treddy/bin:/home/treddy/github_projects/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/openblas-0.3.26-gt4gcloeyzvdir73ryejeuo34h6l4jfr/bin:/home/treddy/github_projects/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/openblas-0.3.26-gt4gcloeyzvdir73ryejeuo34h6l4jfr/bin:/home/treddy/github_projects/spack/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/treddy/.local/bin:/home/treddy/.local/bin HOME=/home/treddy/home/treddy/python_venvs/py_311_bench_ecr/bin/python3 /home/treddy/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py /home/treddy/.modular/pkg/packages.modular.com_mojo /home/treddy/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt`
	- Result: 1
	- Stderr:
An error occurred when installing Python dependencies:
stdout:

stderr:


Traceback (most recent call last):
  File "/home/treddy/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 75, in <module>
    main()
  File "/home/treddy/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 63, in main
    _check_call(
  File "/home/treddy/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 34, in _check_call
    raise e
  File "/home/treddy/.modular/pkg/packages.modular.com_mojo/scripts/post-install/install-dependencies.py", line 22, in _check_call
    subprocess.run(
  File "/home/treddy/github_projects/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/python-3.11.7-576sy6uczetw3xyazw7g5tta7ei4s5jl/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/home/treddy/.modular/pkg/packages.modular.com_mojo/venv/bin/python', '-m', 'pip', 'install', '-r', '/home/treddy/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt')' died with <Signals.SIGSEGV: 11>.


==========================

```

</details>

**Comment by ematejska** [comment]
Looks like this happens before the mojo post install tests. @smuniraj2018

**Comment by ematejska** [comment]
Thank you for trying out Mojo.  The installation experience has significantly changed and we're closing out all the old issues with the old installer.  To try out our new installation experience using "magic", please see: https://docs.modular.com/mojo/manual/get-started.
