### ISSUE TITLE
[BUG]: 'URL fetch failure' while accessing mnist dataset from keras.datasets module on playground server

### ISSUE THREAD

**Issue by chinya07** [modularml/mojo#329]
### Bug description

```shell
I am encountering an issue with network connectivity, receiving an `URL fetch` unreachable network error after a significant delay when attempting to load the mnist dataset from the keras.datasets module in python mode.
PS: No issue loading keras!

Cell output:

`2023-06-05 22:30:10.096086: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-06-05 22:30:10.097962: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-05 22:30:10.134659: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-05 22:30:10.135027: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-05 22:31:34.414056: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/conda/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/opt/conda/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/opt/conda/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/opt/conda/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/opt/conda/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/keras/utils/data_utils.py", line 346, in get_file
    urlretrieve(origin, fpath, DLProgbar())
  File "/opt/conda/lib/python3.8/site-packages/keras/utils/data_utils.py", line 85, in urlretrieve
    response = urlopen(url, data)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/conda/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "<string>", line 6, in <module>
  File "/opt/conda/lib/python3.8/site-packages/keras/datasets/mnist.py", line 75, in load_data
    path = get_file(
  File "/opt/conda/lib/python3.8/site-packages/keras/utils/data_utils.py", line 350, in get_file
    raise Exception(error_msg.format(origin, e.errno, e.reason))
Exception: URL fetch failure on https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz: None -- [Errno 101] Network is unreachable
Error: The Python expression raised an exception`
```

### Steps to reproduce

```shell
%%python
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
```

### System information

```shell
11:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2d06ea56_1a1a_4e0b_a1a3_20e3abbc0825.slice/cri-containerd-d6649881319d8c4b282379b288705a9c2820a3837b7871f57ccdd45475fe25d3.scope
10:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2d06ea56_1a1a_4e0b_a1a3_20e3abbc0825.slice/cri-containerd-d6649881319d8c4b282379b288705a9c2820a3837b7871f57ccdd45475fe25d3.scope
9:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2d06ea56_1a1a_4e0b_a1a3_20e3abbc0825.slice/cri-containerd-d6649881319d8c4b282379b288705a9c2820a3837b7871f57ccdd45475fe25d3.scope
8:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2d06ea56_1a1a_4e0b_a1a3_20e3abbc0825.slice/cri-containerd-d6649881319d8c4b282379b288705a9c2820a3837b7871f57ccdd45475fe25d3.scope
7:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2d06ea56_1a1a_4e0b_a1a3_20e3abbc0825.slice/cri-containerd-d6649881319d8c4b282379b288705a9c2820a3837b7871f57ccdd45475fe25d3.scope
6:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2d06ea56_1a1a_4e0b_a1a3_20e3abbc0825.slice/cri-containerd-d6649881319d8c4b282379b288705a9c2820a3837b7871f57ccdd45475fe25d3.scope
5:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2d06ea56_1a1a_4e0b_a1a3_20e3abbc0825.slice/cri-containerd-d6649881319d8c4b282379b288705a9c2820a3837b7871f57ccdd45475fe25d3.scope
4:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2d06ea56_1a1a_4e0b_a1a3_20e3abbc0825.slice/cri-containerd-d6649881319d8c4b282379b288705a9c2820a3837b7871f57ccdd45475fe25d3.scope
3:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2d06ea56_1a1a_4e0b_a1a3_20e3abbc0825.slice/cri-containerd-d6649881319d8c4b282379b288705a9c2820a3837b7871f57ccdd45475fe25d3.scope
2:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2d06ea56_1a1a_4e0b_a1a3_20e3abbc0825.slice/cri-containerd-d6649881319d8c4b282379b288705a9c2820a3837b7871f57ccdd45475fe25d3.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2d06ea56_1a1a_4e0b_a1a3_20e3abbc0825.slice/cri-containerd-d6649881319d8c4b282379b288705a9c2820a3837b7871f57ccdd45475fe25d3.scope
0::/
```

**Comment by Mogball** [comment]
Network connectivity is disabled in the playground.
