### ISSUE TITLE
[BUG]: sns.load_dataset() throws exception

### ISSUE THREAD

**Issue by CC-KEH** [modularml/mojo#480]
### 2 Exception Errors

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/conda/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/opt/conda/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/opt/conda/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/opt/conda/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/opt/conda/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/opt/conda/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "<string>", line 9, in <module>
  File "/opt/conda/lib/python3.8/site-packages/seaborn/utils.py", line 586, in load_dataset
    if name not in get_dataset_names():
  File "/opt/conda/lib/python3.8/site-packages/seaborn/utils.py", line 512, in get_dataset_names
    with urlopen(url) as resp:
  File "/opt/conda/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/conda/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/conda/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
Error: The Python expression raised an exception

### Steps to reproduce

- Name the pre-existing notebook that failed and the steps that led to failure.
- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### System information

```shell
11:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod646cc43c_708f_46b9_9c0e_de1571a01a04.slice/cri-containerd-b0801cc9fa93d0cf889a27088bd3356b5206f4e4b370ecc9fff5f23052e53c4e.scope
10:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod646cc43c_708f_46b9_9c0e_de1571a01a04.slice/cri-containerd-b0801cc9fa93d0cf889a27088bd3356b5206f4e4b370ecc9fff5f23052e53c4e.scope
9:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod646cc43c_708f_46b9_9c0e_de1571a01a04.slice/cri-containerd-b0801cc9fa93d0cf889a27088bd3356b5206f4e4b370ecc9fff5f23052e53c4e.scope
8:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod646cc43c_708f_46b9_9c0e_de1571a01a04.slice/cri-containerd-b0801cc9fa93d0cf889a27088bd3356b5206f4e4b370ecc9fff5f23052e53c4e.scope
7:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod646cc43c_708f_46b9_9c0e_de1571a01a04.slice/cri-containerd-b0801cc9fa93d0cf889a27088bd3356b5206f4e4b370ecc9fff5f23052e53c4e.scope
6:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod646cc43c_708f_46b9_9c0e_de1571a01a04.slice/cri-containerd-b0801cc9fa93d0cf889a27088bd3356b5206f4e4b370ecc9fff5f23052e53c4e.scope
5:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod646cc43c_708f_46b9_9c0e_de1571a01a04.slice/cri-containerd-b0801cc9fa93d0cf889a27088bd3356b5206f4e4b370ecc9fff5f23052e53c4e.scope
4:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod646cc43c_708f_46b9_9c0e_de1571a01a04.slice/cri-containerd-b0801cc9fa93d0cf889a27088bd3356b5206f4e4b370ecc9fff5f23052e53c4e.scope
3:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod646cc43c_708f_46b9_9c0e_de1571a01a04.slice/cri-containerd-b0801cc9fa93d0cf889a27088bd3356b5206f4e4b370ecc9fff5f23052e53c4e.scope
2:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod646cc43c_708f_46b9_9c0e_de1571a01a04.slice/cri-containerd-b0801cc9fa93d0cf889a27088bd3356b5206f4e4b370ecc9fff5f23052e53c4e.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod646cc43c_708f_46b9_9c0e_de1571a01a04.slice/cri-containerd-b0801cc9fa93d0cf889a27088bd3356b5206f4e4b370ecc9fff5f23052e53c4e.scope
0::/
```

**Comment by CC-KEH** [comment]
> Do you have the code that causes this error?

%%python
import seaborn as sns
iris = sns.load_dataset("iris")

**Comment by itzivo** [comment]
> > Do you have the code that causes this error?
> 
> %%python import seaborn as sns iris = sns.load_dataset("iris")

I do not know to much but I can understand a little. I just reason out things a programmer. 
###
Mojo is not a feature-complete superset of Python yet, so some language patterns or features from Python currently do not work. So, you can't always copy-paste Python code and run it in Mojo.
###
