### ISSUE TITLE
[BETA]: `failed to run python`

### ISSUE THREAD

**Issue by sneekyfoxx** [modularml/mojo#564]
### Bug description

When trying to install **mojo** on **Fedora Linux**, during the self test occurs a problem with running Python which causes modular to abort the installation process. Though, I can go into `~/.modular/pkg/packages.modular.com_mojo/bin/` and start the mojo interpreter (which works).

### Steps To Reproduce
``` bash
$ modular install mojo
modular: /lib64/libtinfo.so.6: no version information available (required by modular)

pip installed dependencies .......
----------------------------------

Testing `MODULAR_HOME=/home/sneekyfoxx/.modular`
* `/home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... OK
TEST: `mojo build test_python.mojo`... OK
TEST: `mojo demangle`... OK
TEST: `mojo format`... OK
TEST: `mojo package`... OK
TEST: `mojo test_mandelbrot.mojo`... OK
TEST: `mojo test_python.mojo`... OK
== stdout ==
/home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/lib/mojo-repl-entry-point: /lib64/libtinfo.so.6: no version information available (required by /home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/lib/mojo-repl-entry-point)
Self-test OK!

== stderr ==
/home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/bin/mojo)
/home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/bin/lldb: /lib64/libtinfo.so.6: no version information available (required by /home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/bin/lldb)
/home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/bin/lldb: /lib64/libtinfo.so.6: no version information available (required by /home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/bin/../lib/liblldb.so.18git)
/home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/bin/lldb: /lib64/libpanel.so.6: no version information available (required by /home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/bin/../lib/liblldb.so.18git)
/home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/bin/lldb: /lib64/libncurses.so.6: no version information available (required by /home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/bin/../lib/liblldb.so.18git)

TEST: `mojo repl`... ERROR
Traceback (most recent call last):
  File "/home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 342, in <module>
    main()
  File "/home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 338, in main
    tester.test(args.test_jupyter)
  File "/home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 275, in test
    self.test_mojo_repl()
  File "/home/sneekyfoxx/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 195, in test_mojo_repl
    assert False
AssertionError
modular: error: failed to run python:
```

### System information

```shell
1. What OS did you do install modular CLI/mojo on ?
  - Linux fedora 6.4.13-200.fc38.x86_64

2. Provide version information for Mojo by pasting the output of `mojo -v`
  - ./mojo: /lib64/libtinfo.so.6: no version information available (required by ./mojo)
  - mojo 0.2.1 (64d14e85)


3. Provide Modular CLI version by pasting the output of `modular -v`
  - modular: /lib64/libtinfo.so.6: no version information available (required by modular)
  - modular 0.1.3 (a8f5697b)
```

**Comment by Acumane** [comment]
May I ask why this was closed? There seems to be sufficient interest in this issue ticket

**Comment by vigi99vs** [comment]
Same issue, also on fedora.

**Comment by THEGOLDENPRO** [comment]
yeah same exact exception and I'm also on Fedora, upvoting this.

**Comment by fortunewalla** [comment]
Is the CURL error related to the LIBTINFO?

```
$ modular install mojo
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
modular: error: http error: failed to reach URL https://packages.modular.com/mojo/1.root.json with cURL error Problem with the SSL CA cert (path? access rights?) -
```

### Host Info.

```
$ modular host-info
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
  Host Information
  ================

  Target Triple: x86_64-unknown-linux
  CPU: skylake
  CPU Features: 64bit, adx, aes, avx, avx2, bmi, bmi2, clflushopt, cmov, crc32, cx16, cx8, f16c, fma, fsgsbase, fxsr, invpcid, lzcnt, mmx, movbe, pclmul, popcnt, prfchw, rdrnd, rdseed, sahf, sgx, sse, sse2, sse3, sse4.1, sse4.2, ssse3, x87, xsave, xsavec, xsaveopt, xsaves
```
### Full install process

```
$ curl https://get.modular.com | \
  MODULAR_AUTH=mut_43703717572546048e70e9089589557f \
  sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3176  100  3176    0     0   3493      0 --:--:-- --:--:-- --:--:--  3490
[sudo] password for rhh:
Executing the  setup script for the 'modular/installer' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'rpm' ...
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=rhel  version=9.2  codename=Plow  arch=x86_64
 >>>>:
   OK: Importing 'modular/installer' repository GPG keys into rpm ...
   OK: Checking for available package manager (DNF/Microdnf/YUM/Zypper) ...
 ^^^^: ... Detected package manager as 'dnf'
   OK: Checking for dnf dependency 'dnf-plugins-core' ...
   OK: Checking if upstream install config is OK ...
   OK: Fetching 'modular/installer' repository configuration ...
   OK: Installing 'modular/installer' repository via dnf ...
Importing GPG key 0x7A3895AD:
 Userid     : "Cloudsmith Package (modular/installer) <support@cloudsmith.io>"
 Fingerprint: 0BAB A1B0 518C 87CF F4CC 3740 0E49 2573 7A38 95AD
 From       : https://dl.modular.com/public/installer/gpg.0E4925737A3895AD.key
Importing GPG key 0x7A3895AD:
 Userid     : "Cloudsmith Package (modular/installer) <support@cloudsmith.io>"
 Fingerprint: 0BAB A1B0 518C 87CF F4CC 3740 0E49 2573 7A38 95AD
 From       : https://dl.modular.com/public/installer/gpg.0E4925737A3895AD.key
Importing GPG key 0x7A3895AD:
 Userid     : "Cloudsmith Package (modular/installer) <support@cloudsmith.io>"
 Fingerprint: 0BAB A1B0 518C 87CF F4CC 3740 0E49 2573 7A38 95AD
 From       : https://dl.modular.com/public/installer/gpg.0E4925737A3895AD.key
   OK: Updating the dnf cache to fetch the new repository metadata ...
   OK: The repository has been installed successfully - You're ready to rock!


Installed:
  modular-0.1.4-1.x86_64

modular: /lib64/libtinfo.so.6: no version information available (required by modular)
  __  __           _       _
 |  \/  | ___   __| |_   _| | __ _ _ __
 | |\/| |/ _ \ / _` | | | | |/ _` | '__|
 | |  | | (_) | (_| | |_| | | (_| | |
 |_|  |_|\___/ \__,_|\__,_|_|\__,_|_|

Welcome to the Modular CLI!
For info about this tool, type "modular --help".

To install Mojo�, type "modular install mojo".

For Mojo documentation, see https://docs.modular.com/mojo.
To chat on Discord, visit https://discord.gg/modular.
To report issues, go to https://github.com/modularml/mojo/issues.
```

**Comment by arthurbg951** [comment]
Same problem here!

**Comment by onegentig** [comment]
Same issue here on Fedora Linux 37.

<details>

<summary><code>$ modular install mojo</code></summary>

```sh
modular: /usr/lib64/libtinfo.so.6: no version information available (required by modular)
❯ modular install mojo
modular: /usr/lib64/libtinfo.so.6: no version information available (required by modular)
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/onegen/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: find_libpython==0.3.0 in /home/onegen/.local/lib/python3.11/site-packages (from -r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 1)) (0.3.0)
Requirement already satisfied: papermill==2.4.0 in /home/onegen/.local/lib/python3.11/site-packages (from -r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: jupyter_client>=8.3.0 in /home/onegen/.local/lib/python3.11/site-packages (from -r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (8.3.1)
Requirement already satisfied: ansiwrap in /home/onegen/.local/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.4)
Requirement already satisfied: click in /usr/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.1.3)
Requirement already satisfied: pyyaml in /usr/lib64/python3.11/site-packages (from papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (6.0)
Requirement already satisfied: nbformat>=5.1.2 in /home/onegen/.local/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (5.9.2)
Requirement already satisfied: nbclient>=0.2.0 in /home/onegen/.local/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: tqdm>=4.32.2 in /usr/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.66.1)
Requirement already satisfied: requests in /usr/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.28.2)
Requirement already satisfied: entrypoints in /usr/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.3)
Requirement already satisfied: tenacity in /home/onegen/.local/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.2.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: pyzmq>=23.0 in /usr/lib64/python3.11/site-packages (from jupyter_client>=8.3.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (24.0.1)
Requirement already satisfied: tornado>=6.2 in /usr/lib64/python3.11/site-packages (from jupyter_client>=8.3.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (6.2)
Requirement already satisfied: traitlets>=5.3 in /usr/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.9.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter_client>=8.3.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.6.0)
Requirement already satisfied: fastjsonschema in /home/onegen/.local/lib/python3.11/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.18.0)
Requirement already satisfied: jsonschema>=2.6 in /home/onegen/.local/lib/python3.11/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.19.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.11/site-packages (from python-dateutil>=2.8.2->jupyter_client>=8.3.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: textwrap3>=0.9.2 in /home/onegen/.local/lib/python3.11/site-packages (from ansiwrap->papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.9.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.11/site-packages (from requests->papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests->papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.11/site-packages (from requests->papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (1.26.16)
Requirement already satisfied: attrs>=22.2.0 in /home/onegen/.local/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/onegen/.local/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /home/onegen/.local/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /home/onegen/.local/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.10.0)
Testing `MODULAR_HOME=/home/onegen/.modular`
* `/home/onegen/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... OK
TEST: `mojo build test_python.mojo`... OK
TEST: `mojo demangle`... OK
TEST: `mojo format`... OK
TEST: `mojo package`... OK
TEST: `mojo test_mandelbrot.mojo`... OK
TEST: `mojo test_python.mojo`... OK
== stdout ==
/home/onegen/.modular/pkg/packages.modular.com_mojo/lib/mojo-repl-entry-point: /lib64/libtinfo.so.6: no version information available (required by /home/onegen/.modular/pkg/packages.modular.com_mojo/lib/mojo-repl-entry-point)
Self-test OK!

== stderr ==
/home/onegen/.modular/pkg/packages.modular.com_mojo/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /home/onegen/.modular/pkg/packages.modular.com_mojo/bin/mojo)
/home/onegen/.modular/pkg/packages.modular.com_mojo/bin/lldb: /lib64/libtinfo.so.6: no version information available (required by /home/onegen/.modular/pkg/packages.modular.com_mojo/bin/lldb)
/home/onegen/.modular/pkg/packages.modular.com_mojo/bin/lldb: /lib64/libtinfo.so.6: no version information available (required by /home/onegen/.modular/pkg/packages.modular.com_mojo/bin/../lib/liblldb.so.18git)
/home/onegen/.modular/pkg/packages.modular.com_mojo/bin/lldb: /lib64/libpanel.so.6: no version information available (required by /home/onegen/.modular/pkg/packages.modular.com_mojo/bin/../lib/liblldb.so.18git)
/home/onegen/.modular/pkg/packages.modular.com_mojo/bin/lldb: /lib64/libncurses.so.6: no version information available (required by /home/onegen/.modular/pkg/packages.modular.com_mojo/bin/../lib/liblldb.so.18git)

TEST: `mojo repl`... ERROR
Traceback (most recent call last):
  File "/home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 342, in <module>
    main()
  File "/home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 338, in main
    tester.test(args.test_jupyter)
  File "/home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 275, in test
    self.test_mojo_repl()
  File "/home/onegen/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 195, in test_mojo_repl
    assert False
AssertionError
modular: error: failed to run python:
```

</details>

<details>

<summary><code>$ inxi -F</code></summary>

```
System:
  Host: fedora Kernel: 6.4.14-200.fc38.x86_64 arch: x86_64 bits: 64
    Desktop: GNOME v: 44.4 Distro: Fedora release 38 (Thirty Eight)
Machine:
  Type: Desktop System: Gigabyte product: Z270X-Ultra Gaming v: N/A
    serial: <superuser required>
  Mobo: Gigabyte model: Z270X-Ultra Gaming-CF v: x.x
    serial: <superuser required> UEFI: American Megatrends v: F8
    date: 10/27/2017
CPU:
  Info: quad core model: Intel Core i7-6700 bits: 64 type: MT MCP cache:
    L2: 1024 KiB
  Speed (MHz): avg: 3818 min/max: 800/4000 cores: 1: 3826 2: 3756 3: 3849
    4: 3885 5: 3877 6: 3756 7: 3793 8: 3802
Graphics:
  Device-1: NVIDIA GP107 [GeForce GTX 1050] driver: nvidia v: 535.104.05
  Display: x11 server: X.Org v: 1.20.14 with: Xwayland v: 22.1.9 driver: X:
    loaded: nvidia unloaded: fbdev,modesetting,nouveau,vesa
    gpu: nvidia,nvidia-nvswitch resolution: 1920x1080
  API: OpenGL v: 4.6.0 NVIDIA 535.104.05 renderer: NVIDIA GeForce GTX
    1050/PCIe/SSE2
Audio:
  Device-1: Intel 200 Series PCH HD Audio driver: snd_hda_intel
  Device-2: NVIDIA GP107GL High Definition Audio driver: snd_hda_intel
  Device-3: Trust GXT 258 Microphone
    driver: hid-generic,snd-usb-audio,usbhid type: USB
  API: ALSA v: k6.4.14-200.fc38.x86_64 status: kernel-api
  Server-1: PipeWire v: 0.3.79 status: active
Network:
  Device-1: Intel Ethernet I219-V driver: e1000e
  IF: enp0s31f6 state: up speed: 1000 Mbps duplex: full
    mac: 1c:1b:0d:97:f8:f7
Bluetooth:
  Device-1: Cambridge Silicon Radio Bluetooth Dongle (HCI mode) driver: btusb
    type: USB
  Report: btmgmt ID: hci0 state: up address: 33:03:30:09:94:67 bt-v: 4.0
Drives:
  Local Storage: total: 2.69 TiB used: 1.3 TiB (48.2%)
  ID-1: /dev/sda vendor: Samsung model: SSD 870 QVO 1TB size: 931.51 GiB
  ID-2: /dev/sdb vendor: Western Digital model: WD1003FZEX-00K3CA0
    size: 931.51 GiB
  ID-3: /dev/sdc vendor: SanDisk model: EMTEC X150 960GB size: 894.25 GiB
Partition:
  ID-1: / size: 143.62 GiB used: 25.3 GiB (17.6%) fs: ext4 dev: /dev/dm-0
  ID-2: /boot size: 877.5 MiB used: 288.7 MiB (32.9%) fs: ext4
    dev: /dev/sda6
  ID-3: /boot/efi size: 99.8 MiB used: 17.3 MiB (17.4%) fs: vfat
    dev: /dev/sda2
  ID-4: /home size: 190.87 GiB used: 72.41 GiB (37.9%) fs: ext4
    dev: /dev/dm-1
Swap:
  ID-1: swap-1 type: zram size: 8 GiB used: 512 KiB (0.0%) dev: /dev/zram0
  ID-2: swap-2 type: partition size: 4.66 GiB used: 0 KiB (0.0%)
    dev: /dev/sda8
Sensors:
  System Temperatures: cpu: 50.0 C mobo: N/A gpu: nvidia temp: 38 C
  Fan Speeds (rpm): N/A gpu: nvidia fan: 35%
Info:
  Processes: 359 Uptime: 44m Memory: total: 16 GiB available: 15.56 GiB
  used: 5.32 GiB (34.2%) Shell: Zsh inxi: 3.3.29
```

</details>

**Comment by leath-dub** [comment]
Please mojo devs, can you not save us time looking in github issues: I feel like support should be listed properly, not just blanket "linux". Unless you want to put the time into supporting linux, be specific !

Also without the source code can't even try to fix this myself, you have a github, youll be getting the same number of issues. Just release the source !

**Comment by smuniraj2018** [comment]
Thanks for your feedback. We are looking to support new OS in the future. In the meantime, please refer to the documentation for the current OS requirements -> https://docs.modular.com/engine/get-started#requirements and https://docs.modular.com/mojo/manual/get-started/#system-requirements

**Comment by hidara2000** [comment]
The below works for me on Fedora 40 

https://github.com/modularml/mojo/issues/855#issuecomment-2116834443

**Comment by Qarqor5555555** [comment]
MODULAR_AUTH=mut_xxxxxxx
How??????
How to get the key
