### ISSUE TITLE
[BUG]: Cannot run Mojo in VSCode notebooks

### ISSUE THREAD

**Issue by patchie** [modularml/mojo#632]
### Bug description

Running VSCode insiders on win11 insiders.
Using WSL2.

Trying to run hello world in a vscode notebook
![image](https://github.com/modularml/mojo/assets/1792727/a6c6859a-907b-4436-bb44-e3403d4a3936)

Error message:

> The kernel died. Error: Traceback (most recent call last):
>   File "/root/.local/share/jupyter/kernels/mojo-jupyter-kernel/mojokernel.py", line 26, in <module>
>     from ipykernel.kernelapp import IPKernelApp
> ModuleNotFoundError: No module named 'ipykernel'... View Jupyter [log](command:jupyter.viewOutput) for further details.

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

### System information

```shell
- What OS did you do install Mojo on ? Win11 insiders, WSL2
- Provide version information for Mojo by pasting the output of `mojo -v`: mojo 0.2.1 (64d14e85)
- Provide Modular CLI version by pasting the output of `modular -v`: modular 0.1.4 (6b54d308)
```

**Comment by huamichaelchen** [comment]
This is happening on Linux as well, I suspect it's because the mojo kernel did not compiled with `ipykernel`? 

```mojo
Traceback (most recent call last):
  File "~/.local/share/jupyter/kernels/mojo-jupyter-kernel/mojokernel.py", line 26, in <module>
    from ipykernel.kernelapp import IPKernelApp
ModuleNotFoundError: No module named 'ipykernel'
```

**Comment by huamichaelchen** [comment]
Found the way to (somewhat) fix it. It's actually mentioned in their [Basic Python Integration Doc](https://docs.modular.com/mojo/manual/basics/#python-integration). Specifically this section 
![image](https://github.com/modularml/mojo/assets/4327373/67bae89a-4633-4433-9751-6d5427e16938)

However, I don't think the `MOJO_PYTHON_LIBRARY` works in the VSCode scenario. Because `mojo`, at least in my case, when during the installation phase, it chose the system python rather than `conda` python. As you can see in the screenshot, `mojo` kernel in vscode jupyter is actually using `/usr/bin/python3`. 

![Screenshot from 2023-09-09 16-26-47](https://github.com/modularml/mojo/assets/4327373/ed54f9c3-a42f-4f80-b1dd-9d35d17d6618)

So I think you either have to go the "hard way" to modify the `python_lib` in the `~/.modular/modular.cfg`. (I have not tried... not sure if that would break certain linkage or not). So I opt for the easier route, just install `ipykernel` in whichever python environment `mojo` picked up during the installation phase.

```
$ cat ~/.modular/modular.cfg 
[installed]
packages_modular_com_mojo = /home/mars/.modular/pkg/packages.modular.com_mojo

[mojo]
compilerrt_path = /home/mars/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRTShared.so.18git
compilerrt_static_path = /home/mars/.modular/pkg/packages.modular.com_mojo/lib/libKGENCompilerRT-static.a
driver_path = /home/mars/.modular/pkg/packages.modular.com_mojo/bin/mojo
import_path = /home/mars/.modular/pkg/packages.modular.com_mojo/lib/mojo
lldb_visualizers_path = /home/mars/.modular/pkg/packages.modular.com_mojo/lib/lldb-visualizers
lldb_vscode_path = /home/mars/.modular/pkg/packages.modular.com_mojo/bin/lldb-vscode
lsp_server_path = /home/mars/.modular/pkg/packages.modular.com_mojo/bin/mojo-lsp-server
mblack_path = /home/mars/.modular/pkg/packages.modular.com_mojo/lib/mblack/mblack
orcrt_path = /home/mars/.modular/pkg/packages.modular.com_mojo/lib/liborc_rt.a
python_lib = /usr/lib/x86_64-linux-gnu/libpython3.10.so.1.0
repl_entry_point = /home/mars/.modular/pkg/packages.modular.com_mojo/lib/mojo-repl-entry-point
system_libs = -lrt,-ldl,-lpthread,-lm,-lz,-ltinfo

```

Now I can run most cells in the notebook with `mojo` kernel, except the Python Integration part.

![image](https://github.com/modularml/mojo/assets/4327373/fd316de2-1ddd-4af0-82fe-a23717ae186f)

![image](https://github.com/modularml/mojo/assets/4327373/7eeb2bc6-c98a-4c12-a621-008867f51155)

It complains about: Import "python" could not be resolvedPylance[reportMissingImports](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportMissingImports)

**Comment by patchie** [comment]
Yep, it worked when i installed ipykernel on the python instance that mojo is using.

> /usr/bin/python3 -m pip install ipykernel

**Comment by ubergonmx** [comment]
> Also, on a side note, it seems on `WSL1` and `2 core 32GB RAM` Github codespaces, both seem to be stuck at the following line:

I got the same issue with 2-core but switching the Codespace instance to 4-core (16 GB RAM) in my case actually solved it.

**Comment by walter-erquinigo** [comment]
We've made several changes to notebooks in the past months, so this shouldn't be an issue anymore. Please reopen if the issue persists.

**Comment by clumsycomputer** [comment]
> We've made several changes to notebooks in the past months, so this shouldn't be an issue anymore. Please reopen if the issue persists.

are you aware of anyone successfully using `ipywidgets` inside the mojo kernel?

**Comment by walter-erquinigo** [comment]
> > We've made several changes to notebooks in the past months, so this shouldn't be an issue anymore. Please reopen if the issue persists.
> 
> are you aware of anyone successfully using `ipywidgets` inside the mojo kernel?

Hi,
I don't know if that is possible now. The mojo kernel doesn't speak the protocol used by anything other than ipython images, so that might be impossible.
We are actively working on invoking mojo from python, and that might make things easier for you.

**Comment by clumsycomputer** [comment]
> > > We've made several changes to notebooks in the past months, so this shouldn't be an issue anymore. Please reopen if the issue persists.
> > 
> > 
> > are you aware of anyone successfully using `ipywidgets` inside the mojo kernel?
> 
> Hi, I don't know if that is possible now. The mojo kernel doesn't speak the protocol used by anything other than ipython images, so that might be impossible. We are actively working on invoking mojo from python, and that might make things easier for you.

groovy, I took a glance at ‘mojokernel.py’ and am trying to figure out if there is a path forward in patching it to enable ipywidgets??
