### ISSUE TITLE
[BUG]: Installation on Github Codespaces hangs

### ISSUE THREAD

**Issue by koaning** [modularml/mojo#663]
### Bug description

I tried installing Mojo and it seems to hang during the tests. 

### Steps to reproduce

I made it to this step: 

```
modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/codespace/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Collecting find_libpython==0.3.0 (from -r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 1))
  Downloading find_libpython-0.3.0-py3-none-any.whl (8.5 kB)
Collecting papermill==2.4.0 (from -r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Downloading papermill-2.4.0-py3-none-any.whl (38 kB)
Requirement already satisfied: jupyter_client>=8.3.0 in /home/codespace/.local/lib/python3.10/site-packages (from -r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (8.3.1)
Collecting ansiwrap (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Downloading ansiwrap-0.8.4-py2.py3-none-any.whl (8.5 kB)
Collecting click (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for click from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: pyyaml in /home/codespace/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: nbformat>=5.1.2 in /home/codespace/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (5.9.2)
Requirement already satisfied: nbclient>=0.2.0 in /home/codespace/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.0)
Collecting tqdm>=4.32.2 (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Obtaining dependency information for tqdm>=4.32.2 from https://files.pythonhosted.org/packages/00/e5/f12a80907d0884e6dff9c16d0c0114d81b8cd07dc3ae54c5e962cc83037e/tqdm-4.66.1-py3-none-any.whl.metadata
  Downloading tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: requests in /home/codespace/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.31.0)
Collecting entrypoints (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)
Requirement already satisfied: tenacity in /home/codespace/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.2.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/codespace/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: pyzmq>=23.0 in /home/codespace/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (25.1.1)
Requirement already satisfied: tornado>=6.2 in /home/codespace/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (6.3.3)
Requirement already satisfied: traitlets>=5.3 in /home/codespace/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.9.0)
Requirement already satisfied: platformdirs>=2.5 in /home/codespace/.local/lib/python3.10/site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (3.10.0)
Requirement already satisfied: fastjsonschema in /home/codespace/.local/lib/python3.10/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.18.0)
Requirement already satisfied: jsonschema>=2.6 in /home/codespace/.local/lib/python3.10/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.19.0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.10/site-packages (from python-dateutil>=2.8.2->jupyter_client>=8.3.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (1.16.0)
Collecting textwrap3>=0.9.2 (from ansiwrap->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2))
  Downloading textwrap3-0.9.2-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codespace/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/codespace/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.22)
Requirement already satisfied: attrs>=22.2.0 in /home/codespace/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/codespace/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /home/codespace/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /home/codespace/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.10.2)
Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 3.2 MB/s eta 0:00:00
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 4.2 MB/s eta 0:00:00
Installing collected packages: textwrap3, find_libpython, tqdm, entrypoints, click, ansiwrap, papermill
Successfully installed ansiwrap-0.8.4 click-8.1.7 entrypoints-0.4 find_libpython-0.3.0 papermill-2.4.0 textwrap3-0.9.2 tqdm-4.66.1
Testing `MODULAR_HOME=/home/codespace/.modular`
* `/home/codespace/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... OK
TEST: `mojo build test_python.mojo`... OK
TEST: `mojo demangle`... OK
TEST: `mojo format`... OK
TEST: `mojo package`... OK
TEST: `mojo test_mandelbrot.mojo`... OK
TEST: `mojo test_python.mojo`... OK
```

And this is where it started hanging for a few minutes. I killed the process and got this hint from the traceback:

```
^CTEST: `mojo repl`... ERROR
Traceback (most recent call last):
  File "/home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 342, in <module>
    main()
  File "/home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 338, in main
    tester.test(args.test_jupyter)
  File "/home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 275, in test
    self.test_mojo_repl()
  File "/home/codespace/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 185, in test_mojo_repl
    out_data, err_data = repl.communicate(
  File "/home/codespace/.python/current/lib/python3.10/subprocess.py", line 1154, in communicate

    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/codespace/.python/current/lib/python3.10/subprocess.py", line 2005, in _communicate
    ready = selector.select(timeout)
  File "/home/codespace/.python/current/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
```

It seems to poll something? Might be that it's stuck somewhere. 

### System information

- What OS did you do install Mojo on ?

Info from codespaces terminal: 

```
> cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

- Provide version information for Mojo by pasting the output of `mojo -v`

Didn't get to that bit. 

- Provide Modular CLI version by pasting the output of `modular -v`

```
> modular -v 
modular 0.1.4 (6b54d308)
```

**Comment by davfre** [comment]
Had the exact same issue (vscode, webclient). Changing the Github codespaces type from 2 core (8 Gb RAM) to 4 core (16 GB RAM) allowed the installation to go through for me.

**Comment by ematejska** [comment]
Did you have a 2-core machine and does the suggestion help if you switch to 4?

**Comment by ubergonmx** [comment]
> I experienced the same issue on Github Codespaces with a 2-core (8 GB RAM) configuration. Changing the Codespace instance to 4-core (16 GB RAM) allowed the installation to go through for me.

Can confirm. My installation got stuck as well on the `TEST`s but switching from 2-core to 4-core solved it.

**Comment by tom-rigelblu** [comment]
I ran into the same issue on gcloud compute engine (with both regular install and docker build).

OS: Canonical, Ubuntu, 20.04 LTS, amd64 focal image built on 2023-09-18

It got stuck on a machine with:
- "e2-standard-2 (2 vCPU, 1 core, 8 GB memory)"

Workaround:
- Upgraded to "e2-highcpu-4 (4 vCPU, 2 core, 4 GB memory)" and it finished quickly.

**Comment by manupatet** [comment]
This got resolved by downloading the latest (perhaps some fix that made this work too), and using `sudo` before `modular install mojo`. I has to clean the installation first with `sudo mojo clean`.

**Comment by jackos** [comment]
Working on 2-core codespaces, make sure to activate a venv of the system Python:
```
/usr/bin/python3 -m venv ~/venv
source ~/venv/bin/activate
```
Then install again.
