### ISSUE TITLE
[Modular CLI]: No such file or directory: 'juju': 'juju'

### ISSUE THREAD

**Issue by mirameshs** [modularml/mojo#666]
### Issue description

i have instaled moji via snapp install mojo --classic

but there is an error in running mojo on ubuntu 
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```
```

~$ mojo
/snap/mojo/148/lib/python3.6/site-packages/pylxd/client.py:23: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography import x509
Traceback (most recent call last):
  File "/snap/mojo/148/bin/mojo", line 33, in <module>
    sys.exit(load_entry_point('mojo==1.0.0', 'console_scripts', 'mojo')())
  File "/snap/mojo/148/bin/mojo", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/snap/mojo/148/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/snap/mojo/148/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/snap/mojo/148/lib/python3.6/site-packages/mojo/__main__.py", line 4, in <module>
    from .cli import main
  File "/snap/mojo/148/lib/python3.6/site-packages/mojo/cli.py", line 22, in <module>
    import mojo.project
  File "/snap/mojo/148/lib/python3.6/site-packages/mojo/project.py", line 14, in <module>
    from .workspace import Workspace
  File "/snap/mojo/148/lib/python3.6/site-packages/mojo/workspace.py", line 6, in <module>
    from .spec import Spec
  File "/snap/mojo/148/lib/python3.6/site-packages/mojo/spec.py", line 11, in <module>
    from .manifest import Manifest
  File "/snap/mojo/148/lib/python3.6/site-packages/mojo/manifest.py", line 4, in <module>
    from . import phase
  File "/snap/mojo/148/lib/python3.6/site-packages/mojo/phase.py", line 16, in <module>
    from . import charm_repo, juju
  File "/snap/mojo/148/lib/python3.6/site-packages/mojo/juju/__init__.py", line 4, in <module>
    from .debuglogs import DebugLogs
  File "/snap/mojo/148/lib/python3.6/site-packages/mojo/juju/debuglogs.py", line 7, in <module>
    from .status import Status
  File "/snap/mojo/148/lib/python3.6/site-packages/mojo/juju/status.py", line 19, in <module>
    version = subprocess.check_output([juju_path, "version"], stderr=devnull, universal_newlines=True)
  File "/snap/mojo/148/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/snap/mojo/148/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/snap/mojo/148/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/snap/mojo/148/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'juju': 'juju'
```

and also :

```
 modular -V
modular: command not found
```

curl command in modular website worked (finished successfully) but modular command also not found

### Steps to reproduce

- Include relevant code snippet that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- Include anything else that might help us debug the issue.

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
- What OS did you install modular CLI on ?
```

**Comment by SimplyYummy** [comment]
Hi @mirameshs, the snap package you installed doesn't look to be the mojo programming language. A quick search online shows a different software. https://mojo.canonical.com

I would suggest you try installing from the official installation location and follow the official mojo setup guide. https://developer.modular.com/signup
https://docs.modular.com/mojo/

**Comment by SimplyYummy** [comment]
To ensure that the modular software is installed correctly, you can manually download the setup script and then run it. This will give you better control and visibility into the installation process.

**Download the Setup Script**: Run the following command to download the setup script into a file named *setup.sh*. Please replace <YOUR-AUTH> with your actual MODULAR_AUTH key.

`curl https://get.modular.com MODULAR_AUTH=<YOUR-AUTH> --output setup.sh`

Inspect the *setup.sh* script in the same directory you ran the above command and see if it has anything in there.

You can also try the manual installation steps on https://developer.modular.com/download

**Comment by SimplyYummy** [comment]
I also noticed your running a old version of python that is not supported by mojo. You have python3.6 but mojo requires python3.8 to 3.10 I believe. The command below should update your python installation.

```
sudo apt update
sudo apt upgrade python3
```

**Comment by SimplyYummy** [comment]
No worries. I your python version on 3.10.12 should be good. Can you provide any error messages from your command in the "Manual installation steps". The command is here https://developer.modular.com/download and looks like:
```
apt-get install -y apt-transport-https &&
...
```
Note: You will need to run it with `sudo` privileges.

**Comment by bzcheeseman** [comment]
It sounds like this has been resolved, please file a new ticket if you have issues in the future.

**Comment by MominIqbal-1234** [comment]
export MODULAR_HOME="$HOME/.modular"
export PATH="$MODULAR_HOME/pkg/packages.modular.com_mojo/bin:$PATH"
