### ISSUE TITLE
Import numpy error

### ISSUE THREAD

**Issue by byte911** [modularml/mojo#696]
```
Type `:mojo help` for further assistance.
1> %%python
2. import numpy as np
3.
Traceback (most recent call last):
  File "/home/nobody/tools/anaconda3/envs/ComfyUI/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/nobody/tools/anaconda3/envs/ComfyUI/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/nobody/tools/anaconda3/envs/ComfyUI/lib/python3.10/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.compat._inspect import getargspec
  File "/home/nobody/tools/anaconda3/envs/ComfyUI/lib/python3.10/site-packages/numpy/compat/__init__.py", line 12, in <module>
    from . import py3k
  File "/home/nobody/tools/anaconda3/envs/ComfyUI/lib/python3.10/site-packages/numpy/compat/py3k.py", line 21, in <module>
    from pathlib import Path
  File "/home/nobody/tools/anaconda3/envs/ComfyUI/lib/python3.10/site-packages/pathlib.py", line 10, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (/home/nobody/tools/anaconda3/envs/ComfyUI/lib/python3.10/collections/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "<string>", line 1, in <module>
  File "/home/nobody/tools/anaconda3/envs/ComfyUI/lib/python3.10/site-packages/numpy/__init__.py", line 141, in <module>
    from . import core
  File "/home/nobody/tools/anaconda3/envs/ComfyUI/lib/python3.10/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/home/nobody/tools/anaconda3/envs/ComfyUI/bin/python3"
  * The NumPy version is: "1.24.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: cannot import name 'Sequence' from 'collections' (/home/nobody/tools/anaconda3/envs/ComfyUI/lib/python3.10/collections/__init__.py)

Error: The Python expression raised an exception
3>
```

**Comment by byte911** [comment]
```
import numpy as np
```

in the python repl, it runs ok.

**Comment by SoUmNerd** [comment]
```
ImportError: cannot import name 'Sequence' from 'collections' (/home/nobody/tools/anaconda3/envs/ComfyUI/lib/python3.10/collections/__init__.py)

```

It is because this part of the code is deprecated. Please open the file `/home/nobody/tools/anaconda3/envs/ComfyUI/lib/python3.10/collections/__init__.py`.
Now change this:
```py
from collections import Sequence
```
To this:
```py
from collections.abc import Sequence
```
Hope it helps!

**Comment by jackos** [comment]
Hi @byte911 this is due to having the wrong python modules on your `sys.path`, if using conda make sure:

Set the env var `MOJO_PYTHON_LIBRARY` to point towards your conda environments libpython, which you can find by changing into the directory returned by `conda info --base`, then looking under `envs/<your-env-name>/lib` and finding libpython.*

Now try to run it again and it should work.

If not please show the output of running this inside a mojo program:

```mojo
from python import Python
def main():
    let sys = Python.import_module("sys")
    for p in sys.path:
        print(p)
```

**Comment by jackos** [comment]
Closing after no reponse

**Comment by sqr00t** [comment]
Hi @jackos thanks for your help in advance, and apologies for reopening this issue, I was following [using mojo with Python](https://www.modular.com/blog/using-mojo-with-python), and on Apple M1 Pro.

I've instead named my conda env `mojo_env`, also using Python 3.10.

There is no `libpython.so` file, but there is  `libpython.dylib`, so I've added this to `MOJO_PYTHON_LIBRARY`.

The full path to this is `/opt/homebrew/Caskroom/miniconda/base/envs/mojo_env/lib/libpython3.10.dylib`

I've also added the following to `~/.modular/modular.cfg`

`python_lib = /opt/homebrew/Caskroom/miniconda/base/envs/mojo_env/lib/libpython3.10.dylib`

> Hi @byte911 this is due to having the wrong python modules on your `sys.path`, if using conda make sure:
> 
> Set the env var `MOJO_PYTHON_LIBRARY` to point towards your conda environments libpython, which you can find by changing into the directory returned by `conda info --base`, then looking under `envs/<your-env-name>/lib` and finding libpython.*
> 
> Now try to run it again and it should work.
> 
> If not please show the output of running this inside a mojo program:
> 
> ```
> from python import Python
> def main():
>     let sys = Python.import_module("sys")
>     for p in sys.path:
>         print(p)
> ```

This works fine in the mojo REPL and my output is as follows:
```
  1> from python import Python 
  2.  
  3. def main(): 
  4.     let sys = Python.import_module("sys") 
  5.     print(sys.prefix) 
  6.      
  7> main() 
  8.  
/opt/homebrew/Caskroom/miniconda/base/envs/mojo_env
  8> 
```
After installing numpy:

```
  8> let np = Python.import_module("numpy") 
  9. a = np.array([1, 2, 3]) 
 10. print(a) 
 11.  
[1 2 3]
(PythonObject) a = {
  (PyObjectPtr) py_object = {
    (DTypePointer[si8]) value = {
      (pointer<scalar<si8>>) address = 0x000000010264e7f0
    }
  }
}
(PythonObject) np = {
  (PyObjectPtr) py_object = {
    (DTypePointer[si8]) value = {
      (pointer<scalar<si8>>) address = 0x0000000102669800
    }
  }
}
 11>  
```

Running:
```
from python import Python

# This is equivalent to Python's `import numpy as np`
let np = Python.import_module("numpy")
a = np.array([1, 2, 3])
```

In a Jupyter notebook I get the following:
```
Error: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/Users/solomonyu/.modular/pkg/packages.modular.com_mojo/lib/mojo-repl-entry-point"
  * The NumPy version is: "1.24.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

Running `main()` in the same notebook, after of course defining the same function first, I get the expected output:
`/opt/homebrew/Caskroom/miniconda/base/envs/mojo_env`
