### ISSUE TITLE
[BUG]: Mojo VS Code extension results in error message at startup

### ISSUE THREAD

**Issue by erictraut** [modularml/mojo#756]
### Bug description

When launching VS Code with the Mojo extension installed, the following error message is reported in the "Debug Console" tab of VS Code:

```
rejected promise not handled within 1 second: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'options' must have the property "port" or "path". Received {}
stack trace: TypeError: The argument 'options' must have the property "port" or "path". Received {}
	at new NodeError (node:internal/errors:399:5)
	at Server.listen (node:net:1923:11)
	at /Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/externalDebugLauncher.js:177:54
	at new Promise (<anonymous>)
	at RpcLaunchServer.<anonymous> (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/externalDebugLauncher.js:177:20)
	at Generator.next (<anonymous>)
	at /Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/externalDebugLauncher.js:13:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/externalDebugLauncher.js:9:12)
	at RpcLaunchServer.listen (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/externalDebugLauncher.js:176:16)
	at MojoDebugContext.updateOrCreateRpcServer (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/debug.js:82:19)
	at new MojoDebugContext (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/debug.js:62:14)
	at MOJOContext.<anonymous> (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/mojoContext.js:68:35)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/mojoContext.js:10:58)
rejected promise not handled within 1 second: TypeError [ERR_INVALID_ARG_VALUE]: The argument 'options' must have the property "port" or "path". Received {}
stack trace: TypeError: The argument 'options' must have the property "port" or "path". Received {}
	at new NodeError (node:internal/errors:399:5)
	at Server.listen (node:net:1923:11)
	at /Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/externalDebugLauncher.js:177:54
	at new Promise (<anonymous>)
	at RpcLaunchServer.<anonymous> (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/externalDebugLauncher.js:177:20)
	at Generator.next (<anonymous>)
	at /Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/externalDebugLauncher.js:13:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/externalDebugLauncher.js:9:12)
	at RpcLaunchServer.listen (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/externalDebugLauncher.js:176:16)
	at MojoDebugContext.updateOrCreateRpcServer (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/debug.js:82:19)
	at new MojoDebugContext (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/debug/debug.js:64:18)
	at MOJOContext.<anonymous> (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/mojoContext.js:68:35)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/eric/.vscode/extensions/modular-mojotools.vscode-mojo-0.2.1/out/mojoContext.js:10:58)
rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
stack trace: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
	at D.normalizeWindowsDriveLetter (/Users/eric/.vscode/extensions/waderyan.gitblame-10.5.0/out/src/index.js:2:7615)
	at D.addFile (/Users/eric/.vscode/extensions/waderyan.gitblame-10.5.0/out/src/index.js:2:7289)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Steps to reproduce

Install the latest Mojo extension.
Relaunch VS Code.
Open the "Debug Console" from the View menu.

![image](https://github.com/modularml/mojo/assets/7040122/fcf99e9e-e1e6-4fce-9a37-2b43aa47a1fe)

### System information

```shell
Installed on Mac OS 13.5.2 (Ventura) on a MacBook Air with Apple M2 Silicon

VS Code is version 1.82.1

Mojo extension is version v.0.2.1
```

**Comment by River707** [comment]
Thanks for reporting this! Seems like the debug server setup stuff needs a few more checks

**Comment by walter-erquinigo** [comment]
I have a fix ready for this that will be out in a future release.
