### ISSUE TITLE
[Modular CLI]: mojo installation fails on Debian (bullseye)

### ISSUE THREAD

**Issue by manupatet** [modularml/mojo#784]
### Issue description

I'm trying to install mojo using `modular install mojo` into a docker image (debian bullseye as base image). It fails with the following error. 

```
TEST: `mojo build test_mandelbrot.mojo`... ERROR
Traceback (most recent call last):
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 342, in <module>
    main()
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 338, in main
    tester.test(args.test_jupyter)
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 270, in test
    self.test_mojo_build()
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 108, in test_mojo_build
    assert "25" in self.run(Path(tmp) / "test_mandelbrot")[0]
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 78, in run
    process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/tmp/tmpy6l9jmmc/test_mandelbrot')
modular: error: failed to run python: 
```

Apart from modular, the docker image includes fllowing packages:
1. Python3
2. Torch
3. torchvision
4. matplotlib
5. pyspark

### Steps to reproduce

- Create a docker-image with Bullseye-slim as base image
- Install modular: `RUN curl https://get.modular.com | MODULAR_AUTH=mut_<your_auth> sh -`
- Install mojo `RUN modular install mojo`

### Version Info

```shell
- Provide Modular CLI version by pasting the output of `modular -v`
  modular 0.1.4 (6b54d308)

- What OS did you install modular CLI on ?
  Debian Bullseye-slim
```

**Comment by blk0** [comment]
Same thing on Ubuntu focal, up-to-date. 

```
$ modular clean
$ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /root/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Requirement already satisfied: find_libpython==0.3.0 in /usr/local/lib/python3.8/dist-packages (from -r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 1)) (0.3.0)
Requirement already satisfied: papermill==2.4.0 in /usr/local/lib/python3.8/dist-packages (from -r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: jupyter_client>=8.3.0 in /usr/local/lib/python3.8/dist-packages (from -r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (8.3.1)
Requirement already satisfied: nbclient>=0.2.0 in /usr/local/lib/python3.8/dist-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.22.0)
Requirement already satisfied: tenacity in /usr/local/lib/python3.8/dist-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.2.3)
Requirement already satisfied: tqdm>=4.32.2 in /usr/local/lib/python3.8/dist-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.66.1)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (7.0)
Requirement already satisfied: ansiwrap in /usr/local/lib/python3.8/dist-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.4)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (5.3.1)
Requirement already satisfied: entrypoints in /usr/lib/python3/dist-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.3)
Requirement already satisfied: nbformat>=5.1.2 in /usr/local/lib/python3.8/dist-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (5.9.2)
Requirement already satisfied: importlib-metadata>=4.8.3; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (6.8.0)
Requirement already satisfied: pyzmq>=23.0 in /usr/local/lib/python3.8/dist-packages (from jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (25.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.8/dist-packages (from jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.8/dist-packages (from jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: traitlets>=5.3 in /usr/local/lib/python3.8/dist-packages (from jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.10.0)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.8/dist-packages (from jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (6.3.3)
Requirement already satisfied: textwrap3>=0.9.2 in /usr/local/lib/python3.8/dist-packages (from ansiwrap->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.9.2)
Requirement already satisfied: fastjsonschema in /usr/local/lib/python3.8/dist-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.18.0)
Requirement already satisfied: jsonschema>=2.6 in /usr/lib/python3/dist-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.2.0)
Requirement already satisfied: zipp>=0.5 in /usr/lib/python3/dist-packages (from importlib-metadata>=4.8.3; python_version < "3.10"->jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (1.14.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.8/dist-packages (from jupyter-core!=5.0.*,>=4.12->jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (3.10.0)
Testing `MODULAR_HOME=/root/.modular`
* `/root/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... ERROR
Traceback (most recent call last):
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 342, in <module>
    main()
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 338, in main
    tester.test(args.test_jupyter)
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 270, in test
    self.test_mojo_build()
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 108, in test_mojo_build
    assert "25" in self.run(Path(tmp) / "test_mandelbrot")[0]
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 78, in run
    process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/tmp/tmp1n7cs139/test_mandelbrot')
modular: error: failed to run python: 

$ uname -a
Linux black 5.4.0-149-generic #166-Ubuntu SMP Tue Apr 18 16:51:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/apt/sources.list | head -n4
# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://de.archive.ubuntu.com/ubuntu focal main restricted
# deb-src http://de.archive.ubuntu.com/ubuntu focal main restricted

```

**Comment by blk0** [comment]
Same thing after upgrade. 

```
$ head /etc/apt/sources.list | head -n5
# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://de.archive.ubuntu.com/ubuntu lunar main restricted
# deb-src http://de.archive.ubuntu.com/ubuntu lunar main restricted
```

Attached is the `modular install mojo` output and `strace -E trace=open,read,write,readv,writev,recv,recvfrom,send,sendto -s 999 $(ps axu|grep modular|awk ' { print $2 } ' | xargs -i echo -n ' -p {}')` output from another tab. 
[2023-09-16-install-mojo-strace.log](https://github.com/modularml/mojo/files/12635417/2023-09-16-install-mojo-strace.log)
[2023-09-16-install-mojo.log](https://github.com/modularml/mojo/files/12635474/2023-09-16-install-mojo.log)

**Comment by blk0** [comment]
Same thing with subprocess catch

```
strace -ff -E trace=open,read,write,readv,writev,recv,recvfrom,send,sendto -s 999 $(ps axu|grep modular|awk ' { print $2 } ' | xargs -i echo -n ' -p {}')
```

[2023-09-16-02-install-mojo-strace.zip](https://github.com/modularml/mojo/files/12639675/2023-09-16-02-install-mojo-strace.zip)
[2023-09-16-02-install-mojo.log](https://github.com/modularml/mojo/files/12639676/2023-09-16-02-install-mojo.log)

**Comment by blk0** [comment]
https://stackoverflow.com/questions/14370489/what-can-cause-a-resource-temporarily-unavailable-on-sock-send-command

**Comment by blk0** [comment]
@railswarm ✌🏼

**Comment by blk0** [comment]
No change with [this](https://github.com/modularml/mojo/issues/779#issuecomment-1718726716) hack

```
root@a-dev-vm:~# cd modular/
root@a-dev-vm:~/modular# . .venv/bin/activate
(.venv) root@a-dev-vm:~/modular# modular clean
(.venv) root@a-dev-vm:~/modular# modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /root/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Requirement already satisfied: find_libpython==0.3.0 in /root/modular/.venv/lib/python3.11/site-packages (from -r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 1)) (0.3.0)
Requirement already satisfied: papermill==2.4.0 in /root/modular/.venv/lib/python3.11/site-packages (from -r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: jupyter_client>=8.3.0 in /root/modular/.venv/lib/python3.11/site-packages (from -r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (8.3.1)
Requirement already satisfied: ansiwrap in /root/modular/.venv/lib/python3.11/site-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.4)
Requirement already satisfied: click in /root/modular/.venv/lib/python3.11/site-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.1.7)
Requirement already satisfied: pyyaml in /root/modular/.venv/lib/python3.11/site-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (6.0.1)
Requirement already satisfied: nbformat>=5.1.2 in /root/modular/.venv/lib/python3.11/site-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (5.9.2)
Requirement already satisfied: nbclient>=0.2.0 in /root/modular/.venv/lib/python3.11/site-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: tqdm>=4.32.2 in /root/modular/.venv/lib/python3.11/site-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.66.1)
Requirement already satisfied: requests in /root/modular/.venv/lib/python3.11/site-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: entrypoints in /root/modular/.venv/lib/python3.11/site-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.4)
Requirement already satisfied: tenacity in /root/modular/.venv/lib/python3.11/site-packages (from papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.2.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /root/modular/.venv/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /root/modular/.venv/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: pyzmq>=23.0 in /root/modular/.venv/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (25.1.1)
Requirement already satisfied: tornado>=6.2 in /root/modular/.venv/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (6.3.3)
Requirement already satisfied: traitlets>=5.3 in /root/modular/.venv/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.10.0)
Requirement already satisfied: platformdirs>=2.5 in /root/modular/.venv/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (3.10.0)
Requirement already satisfied: fastjsonschema in /root/modular/.venv/lib/python3.11/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.18.0)
Requirement already satisfied: jsonschema>=2.6 in /root/modular/.venv/lib/python3.11/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.19.0)
Requirement already satisfied: six>=1.5 in /root/modular/.venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->jupyter_client>=8.3.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: textwrap3>=0.9.2 in /root/modular/.venv/lib/python3.11/site-packages (from ansiwrap->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.9.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/modular/.venv/lib/python3.11/site-packages (from requests->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /root/modular/.venv/lib/python3.11/site-packages (from requests->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/modular/.venv/lib/python3.11/site-packages (from requests->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /root/modular/.venv/lib/python3.11/site-packages (from requests->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.22)
Requirement already satisfied: attrs>=22.2.0 in /root/modular/.venv/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /root/modular/.venv/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /root/modular/.venv/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /root/modular/.venv/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.10.3)
Testing `MODULAR_HOME=/root/.modular`
* `/root/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... OK
TEST: `mojo build test_python.mojo`... OK
TEST: `mojo demangle`... OK
TEST: `mojo format`... OK
TEST: `mojo package`... OK
TEST: `mojo test_mandelbrot.mojo`... OK
TEST: `mojo test_python.mojo`... OK
^CTEST: `mojo repl`... ERROR
Traceback (most recent call last):
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 342, in <module>
    main()
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 338, in main
    tester.test(args.test_jupyter)
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 275, in test
    self.test_mojo_repl()
  File "/root/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 185, in test_mojo_repl
    out_data, err_data = repl.communicate(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 2108, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

(.venv) root@a-dev-vm:~/modular# 
```

```
$ strace -ff -E trace=open,read,write,readv,writev,recv,recvfrom,send,sendto -s 999 $(ps axu|grep modular|awk ' { print $2 } ' | xargs -i echo -n ' -p {}')
```
[2023-09-16-03-install-mojo-strace.log](https://github.com/modularml/mojo/files/12639711/2023-09-16-03-install-mojo-strace.log)

**Comment by blk0** [comment]
Last try, still failing

[2023-09-16-04-install-mojo.log](https://github.com/modularml/mojo/files/12639747/2023-09-16-04-install-mojo.log)

[2023-09-16-04-install-mojo-strace.log](https://github.com/modularml/mojo/files/12639746/2023-09-16-04-install-mojo-strace.log)

**Comment by bzcheeseman** [comment]
It seems like you have a permissions issue and we can't launch our REPL. Handing off to the mojo tooling folks to take a look.

**Comment by pansen** [comment]
You can see in the logs, that all was performed as root.

**Comment by tom-rigelblu** [comment]
Not sure if this is related, but I ran into the later issue posted here where it gets stuck at
"TEST: `mojo test_python.mojo`... OK"

I found a workaround someone posted here [#663 ](url)

**Comment by manupatet** [comment]
This got resolved automatically by downloading the latest and using `sudo`.

Basically rerunning the commands
`RUN curl https://get.modular.com | MODULAR_AUTH=mut_<your_auth> sh -`
`RUN sudo modular clean && sudo modular install mojo`
