### ISSUE TITLE
[Modular CLI]: while running `modular install mojo` the `TEST: 'mojo REPL'`

### ISSUE THREAD

**Issue by mostafatamer11** [modularml/mojo#838]
### Issue description

```txt
mostafa@DESKTOP-2S41G05:/$ modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/mostafa/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: find_libpython==0.3.0 in /home/mostafa/.local/lib/python3.10/site-packages (from -r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 1)) (0.3.0)
Requirement already satisfied: papermill==2.4.0 in /home/mostafa/.local/lib/python3.10/site-packages (from -r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: jupyter_client>=8.3.0 in /home/mostafa/.local/lib/python3.10/site-packages (from -r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (8.3.1)
Requirement already satisfied: tenacity in /home/mostafa/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.2.3)
Requirement already satisfied: click in /home/mostafa/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.1.7)
Requirement already satisfied: entrypoints in /home/mostafa/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.4)
Requirement already satisfied: nbclient>=0.2.0 in /home/mostafa/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (from papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (5.4.1)
Requirement already satisfied: ansiwrap in /home/mostafa/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.4)
Requirement already satisfied: requests in /home/mostafa/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.31.0)
Requirement already satisfied: tqdm>=4.32.2 in /home/mostafa/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.66.1)
Requirement already satisfied: nbformat>=5.1.2 in /home/mostafa/.local/lib/python3.10/site-packages (from papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (5.9.2)
Requirement already satisfied: tornado>=6.2 in /home/mostafa/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (6.3.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/mostafa/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: pyzmq>=23.0 in /home/mostafa/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (25.1.1)
Requirement already satisfied: traitlets>=5.3 in /home/mostafa/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.10.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/mostafa/.local/lib/python3.10/site-packages (from jupyter_client>=8.3.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: platformdirs>=2.5 in /home/mostafa/.local/lib/python3.10/site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter_client>=8.3.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (3.10.0)
Requirement already satisfied: jsonschema>=2.6 in /home/mostafa/.local/lib/python3.10/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.19.0)
Requirement already satisfied: fastjsonschema in /home/mostafa/.local/lib/python3.10/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.18.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->jupyter_client>=8.3.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: textwrap3>=0.9.2 in /home/mostafa/.local/lib/python3.10/site-packages (from ansiwrap->papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.9.2)
Requirement already satisfied: idna<4,>=2.5 in /home/mostafa/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/mostafa/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.0.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/mostafa/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/mostafa/.local/lib/python3.10/site-packages (from requests->papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.22)
Requirement already satisfied: attrs>=22.2.0 in /home/mostafa/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (23.1.0)
Requirement already satisfied: referencing>=0.28.4 in /home/mostafa/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /home/mostafa/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.10.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/mostafa/.local/lib/python3.10/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.1)
Testing `MODULAR_HOME=/home/mostafa/.modular`
* `/home/mostafa/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... OK
TEST: `mojo build test_python.mojo`... OK
TEST: `mojo demangle`... OK
TEST: `mojo format`... OK
TEST: `mojo package`... OK
TEST: `mojo test_mandelbrot.mojo`... OK
TEST: `mojo test_python.mojo`... OK
^C
TEST: `mojo repl`... ERROR
Traceback (most recent call last):
mostafa@DESKTOP-2S41G05:/$   File "/home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 342, in <module>
    main()
  File "/home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 338, in main
    tester.test(args.test_jupyter)
  File "/home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 275, in test
    self.test_mojo_repl()
  File "/home/mostafa/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 185, in test_mojo_repl
    out_data, err_data = repl.communicate(
  File "/usr/lib/python3.10/subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.10/subprocess.py", line 2021, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```
I know i did interrupt it, but its because it just lags
and when I open my task manager my ram isnt full

### Steps to reproduce

write
1 - curl https://get.modular.com | \
  MODULAR_AUTH=mut_546705952b544850a232cf483e594e73 \
  sh -
2 - modular clean
3 - modular install mojo

### Version Info

```shell
- modular 0.1.4 (6b54d308)
- windows 10 wsl ubuntu
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

**Comment by mostafatamer11** [comment]
an interesting thing is when I run mojo files from my bash outside of my ~ dir I get:
```txt
Command 'mojo' not found, but can be installed with:
sudo apt install libmojolicious-perl
```
when I run it from my ~ dir I get:
```txt
[6690:6690:20230918,231134.720708:ERROR exception_handler_server.cc:361] getsockopt: Invalid argument (22)
[6688:6688:20230918,231134.721798:ERROR socket.cc:153] unhandled cmsg 0, 0
Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
```
then typical error messages or output
and the same goes to my vscode terminal
but I can run it from any where

**Comment by Klebestreifen** [comment]
> Is this WSL1 or WSL2? We've had some issues with WSL1 in the past, as well as for machines with low core counts (<4)

I have the same error. I have WSL2 running.

Distro: ´Ubuntu 22.04.3 LTS´

```
klebe@Laptop:~$ uname -a
Linux Laptop 4.4.0-19041-Microsoft #2311-Microsoft Tue Nov 08 17:09:00 PST 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Xanonymous-GitHub** [comment]
After running modular install script, I got this:
```console
48.09 [2551:2551:20231001,224503.553717:ERROR filesystem_posix.cc:63] mkdir /root/.modular/crashdb: No such file or directory (2)
48.09 [2553:2553:20231001,224503.556973:ERROR filesystem_posix.cc:63] mkdir /root/.modular/crashdb: No such file or directory (2)
48.09 [2551:2551:20231001,224503.557551:ERROR socket.cc:120] recvmsg: Connection reset by peer (104)
48.09 Failed to initialize Crashpad.  Crash reporting will not be available.  Cause: crashpad failed to start handler
```

**Comment by srdjanfurman** [comment]
Similar error here in Docker when I was trying to update to v0.5.0 (2023-11-2).

Successfully installed ansiwrap-0.8.4 asttokens-2.4.1 attrs-23.1.0 certifi-2023.7.22 charset-normalizer-3.3.2 click-8.1.7 comm-0.1.4 debugpy-1.8.0 decorator-5.1.1 entrypoints-0.4 exceptiongroup-1.1.3 executing-2.0.1 fastjsonschema-2.18.1 find_libpython-0.3.0 idna-3.4 ipykernel-6.26.0 ipython-8.17.2 jedi-0.19.1 jsonschema-4.19.2 jsonschema-specifications-2023.7.1 jupyter-core-5.5.0 jupyter_client-8.5.0 matplotlib-inline-0.1.6 nbclient-0.8.0 nbformat-5.9.2 nest-asyncio-1.5.8 packaging-23.2 papermill-2.4.0 parso-0.8.3 pexpect-4.8.0 platformdirs-3.11.0 prompt-toolkit-3.0.39 psutil-5.9.6 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.16.1 python-dateutil-2.8.2 pyyaml-6.0.1 pyzmq-25.1.1 referencing-0.30.2 requests-2.31.0 rpds-py-0.10.6 six-1.16.0 stack-data-0.6.3 tenacity-8.2.3 textwrap3-0.9.2 tornado-6.3.3 tqdm-4.66.1 traitlets-5.13.0 urllib3-2.0.7 wcwidth-0.2.9
[mojo] Testing: `mojo repl` [FAIL]
[mojo] Some components may have been installed successfully, but others may not work as expected. Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.
modular: error: failed to run python: 
root@a88156895f15:/#

modular -v
modular 0.2.2 (95d42445)

lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

**Comment by sarang-manohar** [comment]
I have a similar issue

(.venv) root@3eb51d1121a6:~# modular clean && modular install mojo
# Found release for https://packages.modular.com/mojo @ 0.6.0
# Installing to /root/.modular/pkg/packages.modular.com_mojo
# Downloading artifacts. Please wait...
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Collecting find_libpython==0.3.0
  Downloading find_libpython-0.3.0-py3-none-any.whl (8.5 kB)
Collecting jupyter_client>=8.3.0
  Downloading jupyter_client-8.6.0-py3-none-any.whl (105 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.9/105.9 KB 541.6 kB/s eta 0:00:00
Collecting ipykernel>=6.25.0
  Downloading ipykernel-6.27.1-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.6/114.6 KB 1.2 MB/s eta 0:00:00
Collecting traitlets>=5.3
  Downloading traitlets-5.14.0-py3-none-any.whl (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.2/85.2 KB 2.1 MB/s eta 0:00:00
Collecting tornado>=6.2
  Downloading tornado-6.4-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (435 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 435.4/435.4 KB 3.9 MB/s eta 0:00:00
Collecting pyzmq>=23.0
  Downloading pyzmq-25.1.2-cp310-cp310-manylinux_2_28_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 6.0 MB/s eta 0:00:00
Collecting jupyter-core!=5.0.*,>=4.12
  Downloading jupyter_core-5.5.0-py3-none-any.whl (28 kB)
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 11.2 MB/s eta 0:00:00
Collecting psutil
  Downloading psutil-5.9.6-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (283 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.6/283.6 KB 4.4 MB/s eta 0:00:00
Collecting nest-asyncio
  Downloading nest_asyncio-1.5.8-py3-none-any.whl (5.3 kB)
Collecting comm>=0.1.1
  Downloading comm-0.2.0-py3-none-any.whl (7.0 kB)
Collecting ipython>=7.23.1
  Downloading ipython-8.18.1-py3-none-any.whl (808 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 808.2/808.2 KB 4.4 MB/s eta 0:00:00
Collecting packaging
  Downloading packaging-23.2-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 KB 5.8 MB/s eta 0:00:00
Collecting debugpy>=1.6.5
  Downloading debugpy-1.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 8.7 MB/s eta 0:00:00
Collecting matplotlib-inline>=0.1
  Downloading matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting jedi>=0.16
  Downloading jedi-0.19.1-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 9.6 MB/s eta 0:00:00
Collecting prompt-toolkit<3.1.0,>=3.0.41
  Downloading prompt_toolkit-3.0.43-py3-none-any.whl (386 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 386.1/386.1 KB 14.1 MB/s eta 0:00:00
Collecting stack-data
  Downloading stack_data-0.6.3-py3-none-any.whl (24 kB)
Collecting pygments>=2.4.0
  Downloading pygments-2.17.2-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 9.3 MB/s eta 0:00:00
Collecting exceptiongroup
  Downloading exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
Collecting pexpect>4.3
  Downloading pexpect-4.9.0-py2.py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.8/63.8 KB 5.3 MB/s eta 0:00:00
Collecting decorator
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting platformdirs>=2.5
  Downloading platformdirs-4.1.0-py3-none-any.whl (17 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting parso<0.9.0,>=0.8.3
  Downloading parso-0.8.3-py2.py3-none-any.whl (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 KB 8.7 MB/s eta 0:00:00
Collecting ptyprocess>=0.5
  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Downloading wcwidth-0.2.12-py2.py3-none-any.whl (34 kB)
Collecting asttokens>=2.1.0
  Downloading asttokens-2.4.1-py2.py3-none-any.whl (27 kB)
Collecting executing>=1.2.0
  Downloading executing-2.0.1-py2.py3-none-any.whl (24 kB)
Collecting pure-eval
  Downloading pure_eval-0.2.2-py3-none-any.whl (11 kB)
Installing collected packages: wcwidth, pure-eval, ptyprocess, find_libpython, traitlets, tornado, six, pyzmq, pygments, psutil, prompt-toolkit, platformdirs, pexpect, parso, packaging, nest-asyncio, executing, exceptiongroup, decorator, debugpy, python-dateutil, matplotlib-inline, jupyter-core, jedi, comm, asttokens, stack-data, jupyter_client, ipython, ipykernel
Successfully installed asttokens-2.4.1 comm-0.2.0 debugpy-1.8.0 decorator-5.1.1 exceptiongroup-1.2.0 executing-2.0.1 find_libpython-0.3.0 ipykernel-6.27.1 ipython-8.18.1 jedi-0.19.1 jupyter-core-5.5.0 jupyter_client-8.6.0 matplotlib-inline-0.1.6 nest-asyncio-1.5.8 packaging-23.2 parso-0.8.3 pexpect-4.9.0 platformdirs-4.1.0 prompt-toolkit-3.0.43 psutil-5.9.6 ptyprocess-0.7.0 pure-eval-0.2.2 pygments-2.17.2 python-dateutil-2.8.2 pyzmq-25.1.2 six-1.16.0 stack-data-0.6.3 tornado-6.4 traitlets-5.14.0 wcwidth-0.2.12
[mojo] Testing: `mojo repl` [FAIL]
[mojo] Some components may have been installed successfully, but others may not work as expected. Please submit an issue to https://github.com/modularml/mojo and include the full output of the command you just ran.
modular: error: failed to run python: 


(.venv) root@3eb51d1121a6:/# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by jackos** [comment]
Resolved in nightly release by https://github.com/modularml/mojo/commit/b6776222dbd1e2e72a5e6f772d01b35fee7ea0d9. Mojo now finds libpython using the python executable on the top of `PATH`

You can test before the official release with `modular install nightly/mojo`. For environments like vscode codespaces that have a python on the top of `PATH` without a dynamic `libpython.so` you can activate a virtual environment to use a different version before installation e.g. the system Python is able to link to a dynamic libpython: 
```bash
/usr/bin/python3 -m venv ~/venv
source ~/venv/bin/activate
```
Or alternatively create and activate an environment that comes with libpython like `pyenv` or `conda`

Please reopen if you have any further issues.
