### ISSUE TITLE
[BUG]: Error while installing on Fedora 37 - /lib64/libtinfo.so.6: no version information available

### ISSUE THREAD

**Issue by dorfsmay** [modularml/mojo#855]
### Bug description

While running `modular install mojo`, it installs, then start running self-test and dies on the test_maddelbrot.mojo

Then when I try to run mojo, I get:
```
.modular/pkg/packages.modular.com_mojo/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by .modular/pkg/packages.modular.com_mojo/bin/mojo)
```

### Steps to reproduce

- Include relevant code snippet or link to code that did not work as expected.
- If applicable, add screenshots to help explain the problem.
- If using the Playground, name the pre-existing notebook that failed and the steps that led to failure.
- Include anything else that might help us debug the issue.

```
$ modular install mojo
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
# Found release for https://packages.modular.com/mojo @ 0.2.1, installing to /home/yves/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: find_libpython==0.3.0 in /home/yves/.local/lib/python3.11/site-packages (from -r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 1)) (0.3.0)
Requirement already satisfied: papermill==2.4.0 in /home/yves/.local/lib/python3.11/site-packages (from -r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: jupyter_client>=8.3.0 in /home/yves/.local/lib/python3.11/site-packages (from -r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (8.3.1)
Requirement already satisfied: ansiwrap in /home/yves/.local/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.4)
Requirement already satisfied: click in /usr/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.1.3)
Requirement already satisfied: pyyaml in /usr/lib64/python3.11/site-packages (from papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (6.0)
Requirement already satisfied: nbformat>=5.1.2 in /home/yves/.local/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (5.9.2)
Requirement already satisfied: nbclient>=0.2.0 in /home/yves/.local/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: tqdm>=4.32.2 in /home/yves/.local/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.66.1)
Requirement already satisfied: requests in /usr/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.28.1)
Requirement already satisfied: entrypoints in /home/yves/.local/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.4)
Requirement already satisfied: tenacity in /home/yves/.local/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.2.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/yves/.local/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: pyzmq>=23.0 in /home/yves/.local/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (25.1.1)
Requirement already satisfied: tornado>=6.2 in /home/yves/.local/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (6.3.3)
Requirement already satisfied: traitlets>=5.3 in /home/yves/.local/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.10.0)
Requirement already satisfied: platformdirs>=2.5 in /home/yves/.local/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter_client>=8.3.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (3.10.0)
Requirement already satisfied: fastjsonschema in /home/yves/.local/lib/python3.11/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.18.0)
Requirement already satisfied: jsonschema>=2.6 in /home/yves/.local/lib/python3.11/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.19.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.11/site-packages (from python-dateutil>=2.8.2->jupyter_client>=8.3.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: textwrap3>=0.9.2 in /home/yves/.local/lib/python3.11/site-packages (from ansiwrap->papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.9.2)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/lib/python3.11/site-packages (from requests->papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests->papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.11/site-packages (from requests->papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (1.26.16)
Requirement already satisfied: attrs>=22.2.0 in /home/yves/.local/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/yves/.local/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in /home/yves/.local/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in /home/yves/.local/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.10.3)
Testing `MODULAR_HOME=/home/yves/.modular`
* `/home/yves/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... ERROR
Traceback (most recent call last):
  File "/home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 342, in <module>
    main()
  File "/home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 338, in main
    tester.test(args.test_jupyter)
  File "/home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 270, in test
    self.test_mojo_build()
  File "/home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 108, in test_mojo_build
    assert "25" in self.run(Path(tmp) / "test_mandelbrot")[0]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yves/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 78, in run
    process = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/tmp/tmpz14vqu5y/test_mandelbrot')
modular: error: failed to run python: 
$
```

### System information

```shell
- What OS did you do install Mojo on ?
Fedora 37

- Provide version information for Mojo by pasting the output of `mojo -v`
mojo 0.2.1 (64d14e85)

- Provide Modular CLI version by pasting the output of `modular -v`
modular 0.1.4 (6b54d308)
```

**Comment by bzcheeseman** [comment]
We don't officially support Fedora yet. Please stay tuned, please try again once we announce Fedora support.

**Comment by shawal-mbalire** [comment]
Do we have fedora support yet?

**Comment by Sharktheone** [comment]
For me, this looks simmilar to the arch issue. I may look into it, if i have some time. Maybe you can just install this library as a dependency.

**Comment by dorfsmay** [comment]
Version 0.4.0 which came out on 2023/10/05, installs and works on Fedora!

**Comment by wrd-blog** [comment]
I am running Fedora 38 with the same issue: libinfo no version info when I run a mojo script, and, mojo REPL will not run.
I installed mojo on another machine running Xbuntu 22.04 and it works just fine.
Fedora 38
mojo 0.4.0
modular 0.2.1

**Comment by eric-vader** [comment]
Same issue on 

Fedora 38
mojo 0.5.0
modular 0.2.2-1

**Comment by wrd-blog** [comment]
I fixed mine by dumping Fedora and installing xbuntu 22.04. Everything is
working as it should now.
Good luck.

**Comment by Sharktheone** [comment]
Got it running in a VM, I'll add the steps to my [install script for arch](https://github.com/Sharktheone/arch-mojo)

**Comment by liudonghua123** [comment]
@Sharktheone Hi, I tried your script, however, it did not work either.

<details><summary>Details</summary>

```
[root@localhost ~]# tree .modular/
.modular/
├── crashdb
│   ├── attachments
│   ├── completed
│   ├── new
│   ├── pending
│   └── settings.dat
├── modular.cfg
└── pkg
    └── packages.modular.com_mojo
        └── root.json

7 directories, 3 files
[root@localhost ~]# python <(curl -sSL https://raw.githubusercontent.com/Sharktheone/arch-mojo/main/install.py) --fedora
modular-installer                                                                                                                                                                                           209  B/s | 659  B     00:03    
modular-installer-noarch                                                                                                                                                                                    240  B/s | 659  B     00:02    
modular-installer-source                                                                                                                                                                                    308  B/s | 659  B     00:02    
Package binutils-2.35.2-37.el9.x86_64 is already installed.
Dependencies resolved.
============================================================================================================================================================================================================================================
 Package                                                  Architecture                                           Version                                                       Repository                                              Size
============================================================================================================================================================================================================================================
Upgrading:
 binutils                                                 x86_64                                                 2.35.2-42.el9                                                 baseos                                                 4.5 M

Transaction Summary
============================================================================================================================================================================================================================================
Upgrade  1 Package

Total download size: 4.5 M
Is this ok [y/N]: y
Downloading Packages:
binutils-2.35.2-42.el9.x86_64.rpm                                                                                                                                                                           600 kB/s | 4.5 MB     00:07    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                       526 kB/s | 4.5 MB     00:08     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                                                    1/1 
  Upgrading        : binutils-2.35.2-42.el9.x86_64                                                                                                                                                                                      1/2 
  Running scriptlet: binutils-2.35.2-42.el9.x86_64                                                                                                                                                                                      1/2 
  Running scriptlet: binutils-2.35.2-37.el9.x86_64                                                                                                                                                                                      2/2 
  Cleanup          : binutils-2.35.2-37.el9.x86_64                                                                                                                                                                                      2/2 
  Running scriptlet: binutils-2.35.2-37.el9.x86_64                                                                                                                                                                                      2/2 
  Verifying        : binutils-2.35.2-42.el9.x86_64                                                                                                                                                                                      1/2 
  Verifying        : binutils-2.35.2-37.el9.x86_64                                                                                                                                                                                      2/2 
Installed products updated.

Upgraded:
  binutils-2.35.2-42.el9.x86_64                                                                                                                                                                                                             

Complete!
x - debian-binary
x - control.tar.xz
x - data.tar.xz
x - debian-binary
x - control.tar.xz
x - data.tar.xz
x - debian-binary
x - control.tar.xz
x - data.tar.xz
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
modular: error: http error: failed to reach URL https://packages.modular.com/mojo/1.root.json with cURL error Problem with the SSL CA cert (path? access rights?) - 
Please restart your shell or run `source /root/.bashrc `to complete the installation
[root@localhost ~]#
```
</details>

**Comment by Sharktheone** [comment]
Ah, I see the error I've made. I used a wrong lib path, when installing mojo with modular. I can hopefully fix this later. I write here, when I have fixed it.

**Comment by Sharktheone** [comment]
@liudonghua123  Okay, it should be fixed now. It looks like, the main problem, was that the script didn't really handle it when installing mojo on the root user.

**Comment by eric-vader** [comment]
Thanks the script works!

**Comment by liudonghua123** [comment]
@Sharktheone Hi, I still got failure when installation. Any clues?

```
[root@localhost ~]# python <(curl -sSL https://raw.githubusercontent.com/Sharktheone/arch-mojo/main/install.py) --fedora
modular-installer                                                                                                         302  B/s | 659  B     00:02    
modular-installer-noarch                                                                                                  405  B/s | 659  B     00:01    
modular-installer-source                                                                                                  295  B/s | 659  B     00:02    
Package binutils-2.35.2-42.el9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
x - debian-binary
x - control.tar.xz
x - data.tar.xz
x - debian-binary
x - control.tar.xz
x - data.tar.xz
x - debian-binary
x - control.tar.xz
x - data.tar.xz
modular: error: http error: failed to reach URL https://packages.modular.com/mojo/1.root.json with cURL error Problem with the SSL CA cert (path? access rights?) - 
Please restart your shell or run `source /root/.bashrc` to complete the installation
[root@localhost ~]# source /root/.bashrc
[root@localhost ~]#
```

**Comment by Sharktheone** [comment]
> failed to reach URL https://packages.modular.com/mojo/1.root.json

I guess, that's basically #771 or #1113 then. Not sure if this was the issue, where a VPN helped somehow, but you could maybe give it a try.

**Comment by hidara2000** [comment]
The following worked for me and based on 

```
sudo mkdir /opt/missing-mojo-deps
cd /opt/missing-mojo-deps
 
sudo wget https://ftp.debian.org/debian/pool/main/libe/libedit/libedit2_3.1-20221030-2_amd64.deb
sudo ar -xv libedit2_3.1-20221030-2_amd64.deb
sudo tar -xf data.tar.xz                                                                     
sudo wget https://ftp.debian.org/debian/pool/main/n/ncurses/libncurses6_6.4-4_amd64.deb
sudo ar -xv libncurses6_6.4-4_amd64.deb
sudo tar -xf ./data.tar.xz
sudo wget https://ftp.debian.org/debian/pool/main/n/ncurses/libtinfo6_6.4-4_amd64.deb
sudo ar -xv libtinfo6_6.4-4_amd64.deb
sudo tar -xf data.tar.xz

export LD_LIBRARY_PATH=/opt/missing-mojo-deps/lib/x86_64-linux-gnu:/opt/missing-mojo-deps/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

```

then run 
```
mojo
```

you can also append 
```
export LD_LIBRARY_PATH=/opt/missing-mojo-deps/lib/x86_64-linux-gnu:/opt/missing-mojo-deps/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
```

to your ~/.zshrc or ~/.bashrc file

**Comment by text-adi** [comment]
> LD_LIBRARY_PATH is only set when mojo is called

For example, you can do the following:
```
cd ~/.modular/pkg/packages.modular.com_max/bin
mv mojo _mojo
mv max _max
```

then create max and mojo files with the following content:

```
export LD_LIBRARY_PATH=/opt/missing-mojo-deps/lib/x86_64-linux-gnu:/opt/missing-mojo-deps/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
filename=$(basename "$0")
_$filename "$@"
```

After that, set the execution rights:
```
chmod +x mojo max
```

**Comment by jaques-sam** [comment]
I know this was closed a year ago, but now with Fedora 40, it seems the issue got back(?):
From magic shell (started following this tutorial https://docs.modular.com/mojo/manual/get-started):
```
❯ mojo
/home/sam/Repos/own/hello-world/.magic/envs/default/bin/mojo-lldb: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory
```

**Comment by teleporterx** [comment]
@jaques-sam you can give https://github.com/modularml/mojo/issues/3629#issuecomment-2495578802 a try!
