### ISSUE TITLE
[BUG]: Mojo bin (partially/incorrectly) installing on latest version - Mojo error when running hello world - (modular: error: failed to run python:) and (JIT session error: Cannot allocate memory)

### ISSUE THREAD

**Issue by mr-sk** [modularml/mojo#900]
### Bug description

Hello, 

I did submit this to the Discord Mojo chat - we walked through it and they suggested I enter a bug. 
Details on my system:

```
uname -a
Linux ip- 5.19.0-1025-aws #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

(AWS EC2 instance) 

mojo --version
mojo 0.3.0 (f64f9601)

modular --version
modular 0.1.4 (6b54d308)

python3 --version
Python 3.10.12

tail -n 5 ~/.bashrc
export MODULAR_HOME="/home/ubuntu/.modular"
export PATH="/home/ubuntu/.modular/pkg/packages.modular.com_mojo/bin:$PATH"

```

I installed via instructions and updated to latest: 
```
modular clean
modular install mojo
```

And when installing I get the following error:
```
Testing `MODULAR_HOME=/home/ubuntu/.modular`
* `/home/ubuntu/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... OK
TEST: `mojo build test_python.mojo`... OK
TEST: `mojo demangle`... OK
TEST: `mojo format`... OK
TEST: `mojo package`... ERROR
Traceback (most recent call last):
  File "/home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 378, in <module>
    main()
  File "/home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 374, in main
    tester.test(args.test_jupyter)
  File "/home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 309, in test
    self.test_mojo_package()
  File "/home/ubuntu/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 156, in test_mojo_package
    "This is a function in a package"
AssertionError
modular: error: failed to run python:
```

And when executing I get the following error:
```
ubuntu@ip:~$ mojo mojo_test.mojo
JIT session error: Cannot allocate memory
mojo: error: Failed to materialize symbols: { (exec, { main }) }
ubuntu@ip:~$ cat mojo_test.mojo
fn main():
   print("Hello, world!")

ubuntu@ip:~$ mojo
Welcome to Mojo! 🔥

Expressions are delimited by a blank line.
Type `:quit` to exit the REPL and `:mojo help` for further assistance.

  1> :quit
Process 42180 exited with status = 9 (0x00000009) killed
```

**Comment by River707** [comment]
Thanks for reporting this! Can you post the specs of your machine? How much RAM is on the machine you're running?

**Comment by jackos** [comment]
Resolved in nightly release by https://github.com/modularml/mojo/commit/b6776222dbd1e2e72a5e6f772d01b35fee7ea0d9. Mojo now finds libpython using the python executable on the top of `PATH`

You can test before the official release with `modular install nightly/mojo`. For environments like vscode codespaces that have a python on the top of `PATH` without a dynamic `libpython.so` you can activate a virtual environment to use a different version before installation e.g. the system Python is able to link to a dynamic libpython: 
```bash
/usr/bin/python3 -m venv ~/venv
source ~/venv/bin/activate
```
Or alternatively create and activate an environment that comes with libpython like `pyenv` or `conda`

Please reopen if you have any further issues.
