### ISSUE TITLE
[Mojo]: install mojo fails

### ISSUE THREAD

**Issue by SergejGorev** [modularml/mojo#938]
### Issue description

installation of mojo fails on step `TEST: mojo repl`

using `pyenv` with `virtualenv` (not sure if its related)

modular CLI version:
```
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
modular 0.1.4 (6b54d308)
```

system:
```
OS: Fedora Linux 38 (Workstation Edition) x86_64
Host: HP EliteBook 845 G7 Notebook PC
Kernel: 6.4.15-200.fc38.x86_64
Shell: fish 3.6.1
CPU: AMD Ryzen 7 PRO 4750U with Radeon Graphics (16) @ 1.700GHz
GPU: AMD ATI 03:00.0 Renoir
```

`❯ modular install mojo` output:
```
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
# Found release for https://packages.modular.com/mojo @ 0.3.0, installing to /home/sergio/.modular/pkg/packages.modular.com_mojo
# Downloads complete, setting configs...
# Configs complete, running post-install hooks...
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: find_libpython==0.3.0 in /home/sergio/.local/lib/python3.11/site-packages (from -r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 1)) (0.3.0)
Requirement already satisfied: papermill==2.4.0 in /home/sergio/.local/lib/python3.11/site-packages (from -r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: jupyter_client>=8.3.0 in /home/sergio/.local/lib/python3.11/site-packages (from -r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (8.3.1)
Requirement already satisfied: ansiwrap in /home/sergio/.local/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.8.4)
Requirement already satisfied: click in /usr/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.1.3)
Requirement already satisfied: pyyaml in /usr/lib64/python3.11/site-packages (from papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (6.0)
Collecting nbformat>=5.1.2
  Using cached nbformat-5.9.2-py3-none-any.whl (77 kB)
Collecting nbclient>=0.2.0
  Using cached nbclient-0.8.0-py3-none-any.whl (73 kB)
Collecting tqdm>=4.32.2
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Requirement already satisfied: requests in /usr/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.28.2)
Requirement already satisfied: entrypoints in /home/sergio/.local/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.4)
Requirement already satisfied: tenacity in /home/sergio/.local/lib/python3.11/site-packages (from papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (8.2.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/sergio/.local/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (5.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: pyzmq>=23.0 in /home/sergio/.local/lib/python3.11/site-packages (from jupyter_client>=8.3.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (25.1.1)
Collecting tornado>=6.2
  Using cached tornado-6.3.3-cp38-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (427 kB)
Collecting traitlets>=5.3
  Using cached traitlets-5.10.1-py3-none-any.whl (122 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/lib/python3.11/site-packages (from jupyter-core!=5.0.*,>=4.12->jupyter_client>=8.3.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (2.6.0)
Requirement already satisfied: fastjsonschema in /home/sergio/.local/lib/python3.11/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (2.18.0)
Requirement already satisfied: jsonschema>=2.6 in /usr/lib/python3.11/site-packages (from nbformat>=5.1.2->papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (4.17.3)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.11/site-packages (from python-dateutil>=2.8.2->jupyter_client>=8.3.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 3)) (1.16.0)
Requirement already satisfied: textwrap3>=0.9.2 in /home/sergio/.local/lib/python3.11/site-packages (from ansiwrap->papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.9.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/lib/python3.11/site-packages (from requests->papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.11/site-packages (from requests->papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.11/site-packages (from requests->papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (1.26.16)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (22.2.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/lib64/python3.11/site-packages (from jsonschema>=2.6->nbformat>=5.1.2->papermill==2.4.0->-r /home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/requirements.txt (line 2)) (0.19.3)
Installing collected packages: traitlets, tqdm, tornado, nbformat, nbclient
  WARNING: The script tqdm is installed in '/home/sergio/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jupyter-trust is installed in '/home/sergio/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jupyter-execute is installed in '/home/sergio/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed nbclient-0.8.0 nbformat-5.9.2 tornado-6.3.3 tqdm-4.66.1 traitlets-5.10.1
Testing `MODULAR_HOME=/home/sergio/.modular`
* `/home/sergio/.modular/pkg/packages.modular.com_mojo/bin/mojo`...
TEST: `mojo --help`... OK
TEST: `mojo run --help`... OK
TEST: `mojo build test_mandelbrot.mojo`... OK
TEST: `mojo build test_python.mojo`... OK
TEST: `mojo demangle`... OK
TEST: `mojo format`... OK
TEST: `mojo package`... OK
TEST: `mojo test_mandelbrot.mojo`... OK
TEST: `mojo test_python.mojo`... OK
== stdout ==

== stderr ==
/home/sergio/.modular/pkg/packages.modular.com_mojo/bin/mojo: /lib64/libtinfo.so.6: no version information available (required by /home/sergio/.modular/pkg/packages.modular.com_mojo/bin/mojo)
/home/sergio/.modular/pkg/packages.modular.com_mojo/bin/lldb: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory

TEST: `mojo repl`... ERROR
Traceback (most recent call last):
  File "/home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 378, in <module>
    main()
  File "/home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 374, in main
    tester.test(args.test_jupyter)
  File "/home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 311, in test
    self.test_mojo_repl()
  File "/home/sergio/.modular/pkg/packages.modular.com_mojo/scripts/post-install/self-test.py", line 195, in test_mojo_repl
    assert False
AssertionError
modular: error: failed to run python:
```

**Comment by inspiredlabs** [comment]
I can also confirm that `Github:codespaces` hangs here in VSC too.

**Comment by bzcheeseman** [comment]
We don't support fedora yet, but as for the hang, that should be fixed in the next release.

**Comment by liudonghua123** [comment]
I have the same problem on almalinux 9.2.

```
[root@localhost ~]# cat /etc/os-release 
NAME="AlmaLinux"
VERSION="9.2 (Turquoise Kodkod)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.2 (Turquoise Kodkod)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
[root@localhost ~]#
[root@localhost ~]# curl https://get.modular.com | MODULAR_AUTH=mut_xxx sh -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3885  100  3885    0     0   4603      0 --:--:-- --:--:-- --:--:--  4597
Executing the  setup script for the 'modular/installer' repository ...

   OK: Checking for required executable 'curl' ... 
   OK: Checking for required executable 'rpm' ... 
   OK: Detecting your OS distribution and release using system methods ...
 ^^^^: ... Detected/provided for your OS/distribution, version and architecture:
 >>>>:
 >>>>: ... distro=almalinux  version=9.2  codename=Turquoise  arch=x86_64  
 >>>>:
   OK: Importing 'modular/installer' repository GPG keys into rpm ... 
   OK: Checking for available package manager (DNF/Microdnf/YUM/Zypper) ... 
 ^^^^: ... Detected package manager as 'dnf'
   OK: Checking for dnf dependency 'dnf-plugins-core' ... 
   OK: Checking if upstream install config is OK ... 
   OK: Fetching 'modular/installer' repository configuration ... 
   OK: Installing 'modular/installer' repository via dnf ... 
  RUN: Updating the dnf cache to fetch the new repository metadata ...Importing GPG key 0x7A3895AD:
 Userid     : "Cloudsmith Package (modular/installer) <support@cloudsmith.io>"
 Fingerprint: 0BAB A1B0 518C 87CF F4CC 3740 0E49 2573 7A38 95AD
 From       : https://dl.modular.com/public/installer/gpg.0E4925737A3895AD.key
Importing GPG key 0x7A3895AD:
 Userid     : "Cloudsmith Package (modular/installer) <support@cloudsmith.io>"
 Fingerprint: 0BAB A1B0 518C 87CF F4CC 3740 0E49 2573 7A38 95AD
 From       : https://dl.modular.com/public/installer/gpg.0E4925737A3895AD.key
Importing GPG key 0x7A3895AD:
 Userid     : "Cloudsmith Package (modular/installer) <support@cloudsmith.io>"
 Fingerprint: 0BAB A1B0 518C 87CF F4CC 3740 0E49 2573 7A38 95AD
 From       : https://dl.modular.com/public/installer/gpg.0E4925737A3895AD.key
   OK: Updating the dnf cache to fetch the new repository metadata ...
   OK: The repository has been installed successfully - You're ready to rock!


Installed:
  modular-0.2.2-1.x86_64                                                                                                                                                                                                                    

modular: /lib64/libtinfo.so.6: no version information available (required by modular)
  __  __           _       _
 |  \/  | ___   __| |_   _| | __ _ _ __
 | |\/| |/ _ \ / _` | | | | |/ _` | '__|
 | |  | | (_) | (_| | |_| | | (_| | |
 |_|  |_|\___/ \__,_|\__,_|_|\__,_|_|

Welcome to the Modular CLI!
For info about this tool, type "modular --help".

To install Mojo🔥, type "modular install mojo".

For Mojo documentation, see https://docs.modular.com/mojo.
To chat on Discord, visit https://discord.gg/modular.
To report issues, go to https://github.com/modularml/mojo/issues.
[root@localhost ~]# modular install mojo
modular: /lib64/libtinfo.so.6: no version information available (required by modular)
modular: error: http error: failed to reach URL https://packages.modular.com/mojo/1.root.json with cURL error Problem with the SSL CA cert (path? access rights?) - 
[root@localhost ~]#
```

**Comment by Sharktheone** [comment]
I wrote a script for getting mojo running on at least fedora. For almalinux it could also work, but you need to try it. I've posted a link in #855. It's mainly for arch, but there is a option for fedora.

**Comment by md-shaddat-shorav-seyam** [comment]
# how did you fix s0 power problem / suspend problem in 845 g7
